### ISSUE TITLE
ubuntu 19.10 - crashing gnome

### ISSUE THREAD

**Issue by asim-vax** [thestr4ng3r/chiaki#100]
Hi,

If i launch chiaki appImage, it connects, and as soon as i load a game, it crashes my desktop, only way is to swap to another tty and reboot the system

ubuntu 19.10
amd ryzen 1700 + vega 56
mesa 19.2.1

**Comment by asim-vax** [comment]
As a follow up - turned on the TV which the ps4 is connected to whilst remote play is active - using the remote still works, and moving a camera around works, it takes the remote connection ~15 seconds to catch up.

Verbose logging is just
[V] GKCrypt 3 key buf size 0x20000, start offset: 0x11000, populated: 0x20000, min key pos: 0x7611000, last key pos: 0x7621090, generating next chunk
Nothing looks like it's erroring

It crashes the desktop if i try to close chiaki whilst it is trying to catch up it'd seem

**Comment by asim-vax** [comment]
[chiaki_session_2019-11-09_10-01-43-566566.log](https://github.com/thestr4ng3r/chiaki/files/3827136/chiaki_session_2019-11-09_10-01-43-566566.log)
attached log

**Comment by thestr4ng3r** [comment]
That's strange, a regular application only using Qt and OpenGL shouldn't be able to crash your entire desktop environment.
To be clear: You can connect and streaming works in the PS4 menu, but only when you start a game, the crash happens?
Then, what exactly do you mean by "catch up"? Do you still see the stream on screen after the crash and it is 15s delayed or something?

Are you using X or Wayland? Please check your Xorg.0.log or the equivalent for your Wayland session. You may also want to try with this build, which has been built from a more recent environment: https://transfer.sh/9IRjU/Chiaki-v1.1.1-Linux-x86_64.AppImage

**Comment by asim-vax** [comment]
I am using X, i will check Xorg log when I get home.

If i don't interact with my desktop, it takes ~15 seconds to catch up, i.e if i spin the camera, the ps4 connected to the TV moves the camera around, and will only display the latest screen 15 seconds later on the remote display.

However, if i try to interact with the application with my mouse/keyboard, it crashes the desktop and i have to swap to a tty to reboot

Thanks,

**Comment by asim-vax** [comment]
@thestr4ng3r closing this ticket as it no longer crashes with latest build, thanks :)
