### ISSUE TITLE
MaxRetryError?

### ISSUE THREAD

**Issue by sb76117** [thestr4ng3r/chiaki#102]
Trying to obtain my Account ID from the Python script and am getting this exception:

File "/data/user/0/org.qpython.qpy/files/lib/python3.6/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='auth.api.sonyentertainmentnetwork.com', port=443): Max retries exceeded with url: /2.0/oauth/token (Caused by SSLError(SSLError(1, '[SSL: NO_CIPHERS_AVAILABLE] no ciphers available (_ssl.c:841)'),))

I'm using two factor on PSN and running script via QPython on Android if that helps.

Thanks!

**Comment by thestr4ng3r** [comment]
That is most likely an issue with your environment/qpython since it can't establish an ssl connection. If you really want to run the script on Android, I can recommend to use termux. You should be able to use it like this:
```
pkg install python wget
wget https://raw.githubusercontent.com/thestr4ng3r/chiaki/master/scripts/psn-account-id.py
pip install --user requests
python psn-account-id.py
```
For me, this works.

**Comment by sb76117** [comment]
Worked perfectly! Thanks so much!

I thought maybe Sony was doing some sort of crackdown. Also, Termux is so much better than the other more popular emulator on the Play store.

Thanks again!
