### ISSUE TITLE
psn-account-id.py UnicodeEncodeError

### ISSUE THREAD

**Issue by odrevet** [thestr4ng3r/chiaki#103]
Hello, when I run the psn-account-id.py script I got the following error : 

> Traceback (most recent call last):
  File "psn-account-id.py", line 34, in <module>
    print("\u27a1\ufe0f  Open the following URL in your Browser and log in:")
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)

Removing the leading character (arrow) line 34 fixes the issue. 

I also has to remove the leading characters at lines : 38, 47, 57, 60, 65, 69, 79, 83, 90

The python script has been saved in a file with unicode encoding (don't know if that matter), from a save-as in the github raw view.  

Here are more informations about my configuration : 

OS 

> Linux edgar 4.12.0-galliumos #1 SMP PREEMPT Wed Aug 23 18:02:44 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Python 
> Python 3.6.8

**Comment by thestr4ng3r** [comment]
Please try again now.

**Comment by odrevet** [comment]
I have the following error : 
`Traceback (most recent call last):
  File "./psn-account-id.py", line 39, in <module>
    print("\u27a1\ufe0f  Open the following URL in your Browser and log in:")
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
`
After more research it turns out that I had to  
`export PYTHONIOENCODING=utf-8`

The script is also working when I set `PYTHONIOENCODING` to `ascii` (despite the error message) 
I only have the error when the variable is either `unset` or set to `latin-1`

loos like the problem was on my end, sorry about that
