### ISSUE TITLE
PIN Login not worked 

### ISSUE THREAD

**Issue by dkopitsa** [thestr4ng3r/chiaki#104]
PIN Login not working in current version.

    [I] Ctrl connected
    [I] Ctrl received Login PIN request
    [I] Ctrl requested Login PIN
    [I] Session received entered Login PIN, forwarding to Ctrl
    [I] Ctrl received entered Login PIN, sending to console
    [E] Ctrl failed to recv: Resource temporarily unavailable
    [E] Ctrl did not receive session id
    [E] Ctrl has failed, shutting down
    [I] Ctrl stopped

But if I first log locally than I can connect remotly via chiaki.

I made some tests with `git bisect` and found that error first appears in commit 042e6987 Non-blocking content.
Here log from previous commit e2fc84e0

    [I] Ctrl received Login PIN request
    [I] Ctrl requested Login PIN
    [I] Session received entered Login PIN, forwarding to Ctrl
    [I] Ctrl received entered Login PIN, sending to console
    [I] Ctrl received Login message: success
    [W] Received Ctrl Message with unknown type 0x6
    [W] offset 0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f  0123456789abcdef
    [W]      0 00 01                                           ..              
    [I] Ctrl received valid Session Id:     15737325437I4JK4M2VRG2OME7UJIAYM52QTH5A2LMEMM2NVVDQAHVQUS2LKQTNC5F52MKEBSB
    [I] Starting Senkusha
    [I] Takion connecting (version 7)
    [I] Takion enabled Don't Fragment Bit
    [I] Takion sent init
    [I] Takion received init ack with remote tag 0x3c9fd38e, outbound streams: 0x64, inbound     streams: 0x64

**Comment by tarmacalastair** [comment]
I installed Chiaki yesterday (on both Ubuntu Linux and Android) for the first time ever and can only connect to my Playstation account if I have already logged in on the PS4 itself with the controller. Once I have done this then Chiaki will connect.
My PS account does have a PIN associated with it so does this sound like the same issue as you? Sorry, very new to both the PS4 and Chiaki and just trying to get the remote play working for my kids.
