### ISSUE TITLE
0x80108bff

### ISSUE THREAD

**Issue by Elocojr99** [thestr4ng3r/chiaki#109]
[I] Regist starting search
[I] Regist sending search packet
[I] Regist received search response from 10.0.0.12
[I] Regist connected to 10.0.0.12, sending request
[I] Regist waiting for response
[E] Regist received HTTP code 403
[E] Reported Application Reason: 0x80108bff (unknown)
[E] Regist eventually failed

**Comment by thestr4ng3r** [comment]
Duplicate of #105
