### ISSUE TITLE
Question: What input lag supposed to be acceptable

### ISSUE THREAD

**Issue by elvinasp** [thestr4ng3r/chiaki#112]
Question what input lag is supposed to be acceptable from technical implementation view (not game play)?

At the moment even when video resolution reduced to 960x540@30fps, input lag is too big to be playable. When started Diablo III, character does not move, it simply "teleports" from one place to another.  Menu navigation is done with 0.5-2 sec delay and some times button presses are lost.

Console: PS4 Pro
PC: AMD Ryzen 5 2400G, Asus PRIME X370-PRO, 32GB RAM
OS: Linux Mint 19.1 Tessa (kernel updated to 5.1.1-050101-generic to work with AMD Ryzen 5 2400G)
Connection: LAN, 100 Mbps on PS4 side. In logs I do see "Senkusha received Pong, RTT = 0,454 ms", which looks ok for me. 
Chiaki versions tried: 1.1.2, 1.1.1 and 1.0.4

CPU load is around 10-15% during streaming.

Where to start digging for reasons? 

Also, sound is redirected to PS4 controller output. Is this intentional?

**Comment by thestr4ng3r** [comment]
Over Ethernet, the latency is usually almost unnoticeable, so 2s delay is definitely not expected. You might be experiencing the same issue as here: https://github.com/thestr4ng3r/chiaki/issues/32
Build from source or try one of the bionic builds to check.

**Comment by elvinasp** [comment]
> Over Ethernet, the latency is usually almost unnoticeable, so 2s delay is definitely not expected. You might be experiencing the same issue as here: #32
> Build from source or try one of the bionic builds to check.
Yeah, it's alive! :)  Bionic build works as expected - no noticeable input lag. Even at 1080p.

**Comment by thestr4ng3r** [comment]
Nice! Follow #32 about updates regarding this issue.
