### ISSUE TITLE
Command line arguments not working correctly

### ISSUE THREAD

**Issue by witheld9** [thestr4ng3r/chiaki#113]
Currently attempting to use the stream command just refers you to the help

**Comment by tuximail** [comment]
I assume you were using the params the wrong way (like I was). Have a look at https://github.com/thestr4ng3r/chiaki/issues/345 for a reference on how to call Chiaki correctly.

**Comment by thestr4ng3r** [comment]
I'm closing this since a lot has changed in the cli. If you encounter any new problems, feel free to open a new issue.
