### ISSUE TITLE
Account ID script crashes after the first step

### ISSUE THREAD

**Issue by MrDandE** [thestr4ng3r/chiaki#116]
I ran the script but once i entered the url that came with the redirect screen, it crashed. 
![tempsnip](https://user-images.githubusercontent.com/58353777/69896498-f6ca6180-12f4-11ea-99e4-1f193be95672.png)

I'm not that experienced with coding and all that stuff so I might not understand your replies.

**Comment by thestr4ng3r** [comment]
What exactly do you mean by "crash"? If the window just closes, the script was probably successful, but only the window closed. I've updated the script a bit to make it easier to use on Windows, so please try again.

**Comment by MrDandE** [comment]
Thank you so much. It worked!
