### ISSUE TITLE
Add Shutdown function

### ISSUE THREAD

**Issue by die4teoffenbarung** [thestr4ng3r/chiaki#12]
A shutdown function would be great, preferably with timer function

**Comment by thestr4ng3r** [comment]
What exactly do you want to shut down? If it's the console, you can specify that in the PS4's settings.
A timeout for the client on inactivity would also be possible, but what would you need that for?

**Comment by die4teoffenbarung** [comment]
You mean the Powersafe Mode? Yes, I use it ike that but i don't like it and the ability to set the time. (Im on 5.05 btw...) 
It would be nice if you could tell the Program:
Shutdown PS4 in 30 minutes

If it isn't possible, no problem, I'll write a Auto-It script for managing this.

Anyway thanks for your efforts!

**Comment by thestr4ng3r** [comment]
From what I know right now it is not possible. I'll add more info here in case I find out something.
