### ISSUE TITLE
How do I get my Account ID

### ISSUE THREAD

**Issue by CommicKick69ing** [thestr4ng3r/chiaki#120]
I look in the instruction saying to run this python script but there are not instructions on how to use it. I am also not fimilar with python because I rarely use it.

**Comment by CommicKick69ing** [comment]
Never mind once I figured it out it was easy

**Comment by Pinhastest** [comment]
Can you explain how to get it. I cant figure it out

**Comment by CommicKick69ing** [comment]
Make sure python is installed on your pc

Copy the code in to notepad and save it as psn-account-id.txt file

then once its saved go to the and change it to a .py file

Double click the file

The file should run or you did something wrong

then the program should display a link

copy it into your broswer and go to the website and log on

After you login the page should be blank and display redirect

Dont do anything to the page just copy the url displayed in your browser

then copy it into the program and press enter and it should display your
code.
