### ISSUE TITLE
Problem executing application after compiling on Windows 

### ISSUE THREAD

**Issue by interdpth** [thestr4ng3r/chiaki#129]
Hello, upon executing the compiled application I get 

`The application was unable to start correctly`
I am using QT MSVC2017 to build against

I followed the instructions and installed Opus and ffmpeg via VCPkg
```
./vcpkg install opus:x64-windows
./vcpkg install ffmpeg:x64-windows
```

updated the submodules
ran cmake gui to configure the build for x64

Attempted to compile and got the following issues 

```
chiaki\gui\src\avopenglwidget.cpp(168): error C2065: 'GL_PIXEL_UNPACK_BUFFER': undeclared identifier
chiaki\gui\src\avopenglwidget.cpp(169): error C2065: 'GL_PIXEL_UNPACK_BUFFER': undeclared identifier
chiaki\gui\src\avopenglwidget.cpp(171): error C2065: 'GL_PIXEL_UNPACK_BUFFER': undeclared identifier
chiaki\gui\src\avopenglwidget.cpp(171): error C2065: 'GL_MAP_INVALIDATE_BUFFER_BIT': undeclared identifier
hiaki\gui\src\avopenglwidget.cpp(172): error C3536: 'buf': cannot be used before it is initialized
chiaki\gui\src\avopenglwidget.cpp(179): error C2664: 'void *memcpy(void *,const void *,size_t)': cannot convert argument 1 from 'int' to 'void *'
chiaki\gui\src\avopenglwidget.cpp(179): note: Conversion from integral type to pointer type requires reinterpret_cast, C-style cast or function-style cast
chiaki\gui\src\avopenglwidget.cpp(183): error C2664: 'void *memcpy(void *,const void *,size_t)': cannot convert argument 1 from 'int' to 'void *'
chiaki\gui\src\avopenglwidget.cpp(183): note: Conversion from integral type to pointer type requires reinterpret_cast, C-style cast or function-style cast
chiaki\gui\src\avopenglwidget.cpp(186): error C2065: 'GL_PIXEL_UNPACK_BUFFER': undeclared identifier
chiaki\gui\src\avopenglwidget.cpp(189): error C2065: 'GL_R8': undeclared identifier
hiaki\gui\src\avopenglwidget.cpp(189): error C2065: 'GL_RED': undeclared identifier
chiaki\gui\src\avopenglwidget.cpp(192): error C2065: 'GL_PIXEL_UNPACK_BUFFER': undeclared identifier
hiaki\gui\src\avopenglwidget.cpp(269): error C2065: 'GL_R8': undeclared identifier
chiaki\gui\src\avopenglwidget.cpp(269): error C2065: 'GL_RED': undeclared identifier
```

Found the definitions for them, and compiled. 

Chiaka-lib tries to compile as a DLL, so fixed that. 

Then had to link against WindowsApp.lib in order for Chiaka to link. Which I think may be the issue.

Not sure how to proceed from here, do I need to link against a different QT?
Could we get some more indepth steps for Windows?

**Comment by thestr4ng3r** [comment]
Tbh I have no idea what `The application was unable to start correctly` means on Windows. The OpenGL definitions should be provided through Qt in this case, defining them manually will only break things more.

The official windows builds are built using msvc 2017 in msys2:
https://github.com/thestr4ng3r/chiaki/blob/be824917b0eb4e392aaa46517b8b540be8e00a35/.appveyor.yml#L16-L17
with the actual script being here: https://github.com/thestr4ng3r/chiaki/blob/master/scripts/appveyor.sh
You might be able to re-use this script if you adjust the absolute `C:\...` paths inside it.

**Comment by interdpth** [comment]
That helped a lot, sadly after modifying them several times i was still missing cmake configurations and includes. However, this did allow me to build it with cmake gui. I will post things I edited to get further along shortly. But this is good knowledge.

**Comment by interdpth** [comment]
For the future; Configure appveyor.sh for your system, user will need to get QT 5.12, upper will not compile Chiaki as is.
