### ISSUE TITLE
can someone please tell me how to do all of this on linux.

### ISSUE THREAD

**Issue by TheFallenFerret** [thestr4ng3r/chiaki#134]
I have absolutely no idea how to code but i am trying to get my account id and dont understand why i cant run this shit in the terminal. anything would be great.

**Comment by TheFallenFerret** [comment]
![](https://github.githubassets.com/images/icons/emoji/unicode/1f44d.png)

**Comment by thestr4ng3r** [comment]
Duplicate of https://github.com/thestr4ng3r/chiaki/issues/63
