### ISSUE TITLE
Library issue. 

### ISSUE THREAD

**Issue by interdpth** [thestr4ng3r/chiaki#135]
Using the following code I am able to get a Chiaki Session, but it errors out quickly 
```
		thisSession = new ChiakiSession();
		chiaki_lib_init();
		thisLog = new ChiakiLog();
		chiaki_log_init(thisLog, CHIAKI_LOG_ALL & ~CHIAKI_LOG_VERBOSE, chiaki_log_cb_print, nullptr);
		chiaki_opus_decoder_init(&opus_decoder, thisLog);
		ChiakiControllerState keyboard_state;
		memset(&keyboard_state, 0, sizeof(keyboard_state));
		ChiakiConnectInfo chiaki_connect_info;

		chiaki_connect_info.host = hidden;
		chiaki_connect_info.video_profile.height = 16;
		chiaki_connect_info.video_profile.width = 16;
		chiaki_connect_info.video_profile.max_fps = 0x32;
		chiaki_connect_info.video_profile.bitrate = 0x2710;

		memcpy(chiaki_connect_info.regist_key,"hidden", sizeof(chiaki_connect_info.regist_key));
		unsigned char morning[] = { hidden};
		memcpy(chiaki_connect_info.morning, morning, sizeof(chiaki_connect_info.morning));

		memset(&keyboard_state, 0, sizeof(keyboard_state));
	

	   ChiakiErrorCode err = chiaki_session_init(thisSession, &chiaki_connect_info, thisLog); 
	 
	   if (err != CHIAKI_ERR_SUCCESS)
	   {
		   printf("Chiaki Session Init failed: %s", chiaki_error_string(err));
	   }
	   else {
		   printf("Chiaki Session Init Success: %s", chiaki_error_string(err));
	   }
	   ChiakiAudioSink audio_sink;
	   chiaki_session_set_audio_sink(thisSession, &audio_sink);

	   chiaki_session_set_video_sample_cb(thisSession, VideoSampleCb, this);
	   chiaki_session_set_event_cb(thisSession, EventCb, this);


	   err = chiaki_session_start(thisSession);
```

Which I got from the GUI's usage, the Console will connect, then disconnect and the Library will tell me 'CHIAKI_QUIT_REASON_STREAM_CONNECTION_UNKNOWN' coming from `chiaki_stream_connection_run(&session->stream_connection); `in `session_thread_func()`. 
I've been digging through the code and can't figure out what I need to do, if anything after starting the library. I assume session_thread_func() keeps everything alive as that's all I can see. 

So I'm unsure the disconnect between Chiaki Gui and my code. 
![image](https://user-images.githubusercontent.com/1134736/71931968-94227c00-3164-11ea-976e-5ba0cd6384a5.png)

**Comment by thestr4ng3r** [comment]
`StreamConnection streaminfo receive timeout`
This is the relevant part from the log. The PS4 did not send the streaminfo packet.

This is most likely the cause:
```c
chiaki_connect_info.video_profile.height = 16;
chiaki_connect_info.video_profile.width = 16;
chiaki_connect_info.video_profile.max_fps = 0x32;
chiaki_connect_info.video_profile.bitrate = 0x2710;
```
The bitrate can be chosen relatively freely, but the other values must match exactly a configuration that the PS4 supports.
For ease of use, you can use the convenience function `chiaki_connect_video_profile_preset()` to fill your profile, e.g.:
```c
chiaki_connect_video_profile_preset(&chiaki_connect_info.video_profile, CHIAKI_VIDEO_RESOLUTION_PRESET_720p, CHIAKI_VIDEO_FPS_PRESET_60);
```

**Comment by interdpth** [comment]
That was definitely it!
