### ISSUE TITLE
Feature request: Onscreen button hide on Android

### ISSUE THREAD

**Issue by shizet1** [thestr4ng3r/chiaki#136]
Hey i really love the Android app, for me it is working better than the official one. But as i exclusively play with gamepads it would be very handy to make the onscreen gamepad autohide after some time. Or maybe a setting for disabling them.

**Comment by thestr4ng3r** [comment]
This already exists. Swipe from an edge to make the status and navigation bar appear and you should see the "On-screen controls" toggle at the bottom:
![Screenshot_20200108-192447](https://user-images.githubusercontent.com/1460997/72004910-b0014d00-324c-11ea-8dde-48ded460dba0.png)

**Comment by shizet1** [comment]
Oh wow never noticed that, thanks for the info. Then there is nothing more to improve for me 👍
