### ISSUE TITLE
Mobile Data and Stretch display option

### ISSUE THREAD

**Issue by ZjemCiKolege** [thestr4ng3r/chiaki#144]
It's possible to play on mobile data?(for now i can't test blocked ports)? any chance to add Stretch display/low latency audio/microphone(like normal sony app) option? 👍 

*feature enhancement*

**Comment by FearlessSpiff** [comment]
Good news for your "Stretch" request from me: https://github.com/thestr4ng3r/chiaki/pull/146

**Comment by FearlessSpiff** [comment]
And yes you have to tweak your firewall and open:
TCP: 9295
UDP: 9308, 9304, 987, 9296

**Comment by thestr4ng3r** [comment]
Mobile data is supported, display stretch is now available and microphone is tracked in #52
