### ISSUE TITLE
Linux. Dualshock 4 touchpad doesn't work.

### ISSUE THREAD

**Issue by CyberDonk3y** [thestr4ng3r/chiaki#175]
Hi, the dualshock touchpad only works in mouse mode.

**Comment by didix16** [comment]
Hi, as you can see at https://github.com/thestr4ng3r/chiaki#features,
there is something to be implemented. At the moment you can press T key from keyboard to send the input.

**Comment by CyberDonk3y** [comment]
oh, I did not see it. Thanks..!
