### ISSUE TITLE
ps4 controller R2 L2 sensitivity?

### ISSUE THREAD

**Issue by tuxeph** [thestr4ng3r/chiaki#189]
Hej
Nice work
Is there a way of configuring the sensitivity (debounce) on the R2 and L2 buttons. 
I have a lot of repeated actions on these to buttons on all my controllers.
On linux I am using Chiaki, And the debounce is not high enough or not present. 
It is not nice when you try to aim at a taget the trigger goes on and of repeatedly.
On windows with sonys app none of my controllers acts like that.

Game: The Hunter (Call to the wild)
Op: Kubuntu 18.01 / win10
Console: ps4 pro
connection: local 1g

tuxeph

**Comment by flplv** [comment]
PR #243 fixes that.

**Comment by tuxeph** [comment]
Nice work there.
That was a showstopper for me. Now i can play in my favorite system.
when do you expect to generate app images with this change?


thanks for your nice work whit this.
Tuxeph

**Comment by thestr4ng3r** [comment]
Not yet merged
