### ISSUE TITLE
Unknown quit error 

### ISSUE THREAD

**Issue by interdpth** [thestr4ng3r/chiaki#193]
Hello, 
My compiled version of the library suddenly started getting "Unknown Session Request Error" 
The kit is on >7. 
As I had the same console registered in production Chiaki, I tried there and I am getting the same error.

![image](https://user-images.githubusercontent.com/1134736/77254569-c99d1880-6c2f-11ea-9964-7f5aa4e4aefb.png)

Tracing in my library, the initial connection is received, however the event callback only receives CHIAKI_EVENT_QUIT

This has been working reliably for a while and I am unsure why this is suddenly happening.

I am VPN'd to the network with the kit, and I can't re-register the kit at the moment.  So I only have the current registration. Thanks for any ideas. 

My log is 

[2020-03-22 11:29:15:212212] [I] Chiaki Version 1.1.3
[2020-03-22 11:29:15:212212] [I] Controller 0 opened: "XInput Controller"
[2020-03-22 11:29:15:213213] [I] Starting session request
[2020-03-22 11:29:19:718718] [I] Trying to request session from ipremoved
[2020-03-22 11:29:19:731731] [I] Connected to ipremoved
[2020-03-22 11:29:19:731731] [I] Sending session request
[2020-03-22 11:29:19:735735] [E] Reported Application Reason: 0x80108bff (unknown)
[2020-03-22 11:29:19:735735] [I] Session has quit

which is very similar to https://github.com/thestr4ng3r/chiaki/issues/51 but i am already above 7.0 and have been.

**Comment by interdpth** [comment]
I do have a ps4 I have access too, but I am unable to register as well. 
[V] Regist formatted request header:
[V] offset 0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f  0123456789abcdef
[V]      0 50 4f 53 54 20 2f 73 63 65 2f 72 70 2f 72 65 67 POST./sce/rp/reg
[V]     10 69 73 74 20 48 54 54 50 2f 31 2e 31 0d 0a 48 4f ist.HTTP/1.1..HO
[V]     20 53 54 3a 20 31 30 2e 30 2e 32 2e 31 35 0d 0a 55 ST:.ipremoved..U
[V]     30 73 65 72 2d 41 67 65 6e 74 3a 20 72 65 6d 6f 74 ser-Agent:.remot
[V]     40 65 70 6c 61 79 20 57 69 6e 64 6f 77 73 0d 0a 43 eplay.Windows..C
[V]     50 6f 6e 6e 65 63 74 69 6f 6e 3a 20 63 6c 6f 73 65 onnection:.close
[V]     60 0d 0a 43 6f 6e 74 65 6e 74 2d 4c 65 6e 67 74 68 ..Content-Length
[V]     70 3a 20 35 33 30 0d 0a 52 50 2d 56 65 72 73 69 6f :.530..RP-Versio
[V]     80 6e 3a 20 39 2e 30 0d 0a 0d 0a                   n:.9.0....      
[I] Regist starting search
[I] Regist sending search packet
[E] Regist timed out waiting for search response
[E] Regist search failed

**Comment by Te-M** [comment]
I'm not sure if this'll help but I'm not 100% that Chiaki is (currently) working.  [I haven't been able to connect on 2 Win7 PCs (including on old versions)](https://github.com/thestr4ng3r/chiaki/issues/176) nor a version I just built on a fresh Debian 10 for fun.  I thought I saw somebody else online mention something similar fairly recently but I couldn't refind the post unfortunately.

**Comment by thestr4ng3r** [comment]
> I do have a ps4 I have access too, but I am unable to register as well.
> [V] Regist formatted request header:
> [V] offset 0 1 2 3 4 5 6 7 8 9 a b c d e f 0123456789abcdef
> [V] 0 50 4f 53 54 20 2f 73 63 65 2f 72 70 2f 72 65 67 POST./sce/rp/reg
> [V] 10 69 73 74 20 48 54 54 50 2f 31 2e 31 0d 0a 48 4f ist.HTTP/1.1..HO
> [V] 20 53 54 3a 20 31 30 2e 30 2e 32 2e 31 35 0d 0a 55 ST:.ipremoved..U
> [V] 30 73 65 72 2d 41 67 65 6e 74 3a 20 72 65 6d 6f 74 ser-Agent:.remot
> [V] 40 65 70 6c 61 79 20 57 69 6e 64 6f 77 73 0d 0a 43 eplay.Windows..C
> [V] 50 6f 6e 6e 65 63 74 69 6f 6e 3a 20 63 6c 6f 73 65 onnection:.close
> [V] 60 0d 0a 43 6f 6e 74 65 6e 74 2d 4c 65 6e 67 74 68 ..Content-Length
> [V] 70 3a 20 35 33 30 0d 0a 52 50 2d 56 65 72 73 69 6f :.530..RP-Versio
> [V] 80 6e 3a 20 39 2e 30 0d 0a 0d 0a n:.9.0....
> [I] Regist starting search
> [I] Regist sending search packet
> [E] Regist timed out waiting for search response
> [E] Regist search failed

This is unrelated to this issue. Most likely a network issue or the PS4 is not in regist mode.

> I'm not sure if this'll help but I'm not 100% that Chiaki is (currently) working. [I haven't been able to connect (registering seemingly went fine) on 2 Win7 PCs (including on old versions)]

It is working, including fetching the psn account id and regist on 7.02 here. The linked issue is also unrelated to this one.

Please only comment issues where the logs match exactly.

**Comment by Te-M** [comment]
My mistake, the linux error box for that one is the same (the console error was similar but without the packet data).  As an aside, I'm still not able to actually stream on any of the 3 different computers I tried even though registering went through fine for me.

**Comment by interdpth** [comment]
Hello, so I have an update on this.  Other computers on my network are able to register and use the console fine. But my own PC isn't able to for some reason. It's like it sends the packet to the PS4 but the socket shutsdown after. Tried upping the registration time out to 12000 instead of the default 3000. Firewall ports opened. It's crazy. Tried rebooting both pc and the console.

**Comment by interdpth** [comment]
I have fixed half the solution, the one I was having issues with was due to an IP issue. However, my regular PC has no luck doing anything remote play related :/

**Comment by interdpth** [comment]
Good now, had to flush dns and renew ip.
Good library as always.
