### ISSUE TITLE
No Video from stream, using Chiaki v1.1.3 appimage

### ISSUE THREAD

**Issue by UnboundKey** [thestr4ng3r/chiaki#200]
When i try to connect to my PS4, i get audio but no video. 
Here's the log i got running the app image through the terminal and connecting
[log.txt](https://github.com/thestr4ng3r/chiaki/files/4457256/log.txt)

**Comment by thestr4ng3r** [comment]
Judging from the logs, your graphics driver probably doesn't support OpenGL 3.2 core.

**Comment by UnboundKey** [comment]
Restarted my computer, and now OpenGL is recognized, so other than bad framerate, most likely due to large bitrate, it works
