### ISSUE TITLE
Audio crackling on Linux

### ISSUE THREAD

**Issue by sverbist** [thestr4ng3r/chiaki#209]
Whenever I do remote play. I get a crackling audio.
I've tried looking through my audio settings if it's anything I can fix but haven't found a solution so far.
I doubt it's network related since I play on a local wired network. For comparison, steam remote play works fine.

Some hardware info in case it's relevant:
OS: Arch Linux x86_64 
Host: HP ENVY x360 Convertible 15-cn0xxx 
Kernel: 5.6.5-arch3-1 
CPU: Intel i7-8550U (8) @ 4.000GHz 
GPU: Intel UHD Graphics 620 
GPU: NVIDIA GeForce MX150 
 Memory: 15757MiB

**Comment by lsiudut** [comment]
Have you tried to increase audio buffer in the settings menu? Just don't raise it too much to avoid audio lag. 16k works perfectly fine for me.

**Comment by sverbist** [comment]
> Have you tried to increase audio buffer in the settings menu? Just don't raise it too much to avoid audio lag. 16k works perfectly fine for me.

That seems to help. Significantly reduced the crackle. Thanks!
