### ISSUE TITLE
Error with VAAPI on Ryzen/Vega laptop

### ISSUE THREAD

**Issue by Odelpasso** [thestr4ng3r/chiaki#214]
Hello,
I have a HP laptop with Ryzen 2500U + Vega 8 mobile. When i enable vaapi, it does not work, i have this error when i launch the stream from my PS4 :
`Failed to initialize Stream Session: avcodec_get_hw_config failed`

I'm on Debian Unstable 64bits + Mesa 20.0.4

**Comment by thestr4ng3r** [comment]
Do you use the AppImage?

**Comment by Odelpasso** [comment]
Yes, it's the case.

**Comment by thestr4ng3r** [comment]
So I've enabled vaapi for future builds, you can try one here: https://transfer.sh/pge4N/Chiaki-10cc2da15d69efbe572c245adcf41a0ceab49e09-Linux-x86_64.AppImage
But I wouldn't get my hopes up that this will work. These AppImages are built against Ubuntu Xenial for compatibility and it ships ancient libraries. I wasn't able to get vaapi to run with it on Arch and it seems like we are not the only ones having issues with this.
So if you want vaapi, your best bet is to build Chiaki yourself.
