### ISSUE TITLE
avcodec_get_hw_config failed

### ISSUE THREAD

**Issue by jdwininger** [thestr4ng3r/chiaki#216]
When I set '**Hardware decode method:**' to '**vaapi**' in settings I get "**Failed to initialize Stream Session: avcodec_get_hw_config failed**" when trying to connect to my PS4 Pro. Below is the output of 'vainfo' on my system. Hardware encode/decode works under OBS, but that's the only program I have to go off of for testing.

> [jeremy@compy9900k ~]$ vainfo
libva info: VA-API version 1.7.0
libva info: Trying to open /usr/lib64/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_7
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.7 (libva 2.7.0.pre1)
vainfo: Driver version: Mesa Gallium driver 20.0.4 for AMD Radeon VII (VEGA20, DRM 3.36.0, 5.6.6-300.fc32.x86_64, LLVM 10.0.0)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc

If you need any other information about my system or environment please ask.

**Comment by thestr4ng3r** [comment]
If you use the AppImage, this is a duplicate of #214

**Comment by jdwininger** [comment]
My apologizes, I'll move my info over to #214
