### ISSUE TITLE
Android 4.4.2 support?

### ISSUE THREAD

**Issue by Nintoad** [thestr4ng3r/chiaki#220]
This is a dumb low priority request. But I have an ancient "Galaxy Tab 4 SM-T230" stuck on android 4.4.2 that I would love to be able to stream the ps4 on. I used to use it for that before the official RemotePlay app started requiring Android 5.0 as the minimum, and it was just a really nice size for it. 

So I was wondering how much trouble (if it is even possible) it would be to get this working on it? Not surprisingly at the moment trying to install the apk just gives a "parse error".

**Comment by thestr4ng3r** [comment]
Sorry, but 4.4 is way too old to be supported at this point, both with respect to features and security.
You might want to look for a Custom ROM for your device, though availability of such options varies depending on the device.
