### ISSUE TITLE
Can't get into the PS4 on Windows 10

### ISSUE THREAD

**Issue by carlosmax3D** [thestr4ng3r/chiaki#226]
**Environment**
 - OS/Distribution: Windows 10 lastest update
 - Desktop Environment: Native Windows desktop
 - Hardware: Native nVidia driver GeForce GT 730
 - Exact Version or Commit Hash and Installation Method: Prebuild binary version 1.2.0 for windows x86_64

**Describe the bug**
I executed the binary and added the device (it's in the same LAN), I put the pin to syncronice and its successful, then when I try to connect into my PS4 and I get the error "Chiaki Session has quit: Ctrl failed to connect". When I tried more than once I got another error called "Chiaki Session has quit: Remote Play on Console is already in use" but when I tried in my Linux or in my Android I can connect successfully, the issue is only on Windows 10. 
Also, I tried with a past prebuild version to see if its an issue of the new build but I got the same issue.

**To Reproduce**
1. Open Chiaki for windows (prebuilt version 1.2.0)
2. Click on my device

**Expected behavior**
The home of my PS4, like my Linux or my Android device.

**Log Files**
[chiaki_session_2020-05-03_22-10-45-244244.log](https://github.com/thestr4ng3r/chiaki/files/4572643/chiaki_session_2020-05-03_22-10-45-244244.log)
[chiaki_session_2020-05-03_22-11-01-115115.log](https://github.com/thestr4ng3r/chiaki/files/4572644/chiaki_session_2020-05-03_22-11-01-115115.log)
[chiaki_session_2020-05-03_22-11-21-789789.log](https://github.com/thestr4ng3r/chiaki/files/4572645/chiaki_session_2020-05-03_22-11-21-789789.log)
[chiaki_session_2020-05-03_22-11-28-313313.log](https://github.com/thestr4ng3r/chiaki/files/4572646/chiaki_session_2020-05-03_22-11-28-313313.log)
[chiaki_session_2020-05-03_22-11-36-000000.log](https://github.com/thestr4ng3r/chiaki/files/4572647/chiaki_session_2020-05-03_22-11-36-000000.log)
[chiaki_session_2020-05-03_22-12-00-231231.log](https://github.com/thestr4ng3r/chiaki/files/4572648/chiaki_session_2020-05-03_22-12-00-231231.log)

**Screenshots**
![image](https://user-images.githubusercontent.com/15691002/80934101-41607600-8d8c-11ea-812e-a0583b782122.png)

![image](https://user-images.githubusercontent.com/15691002/80934113-4a514780-8d8c-11ea-85e2-06de2ab90c0b.png)

**Additional context**
My Linux and Android device uses a certain PS4 ID, on my windows I use another PS4 ID, I tried in another android device and it works in the android device, the issue is only for Windows 10.

I added chiaki to the firewall and also select the option "accept every connection" and also I deactivate the firewall, same issues.

**Comment by interdpth** [comment]
Is the PS4 on wi-fi or Ethernet?

**Comment by carlosmax3D** [comment]
It's connected over Ethernet and it has an static IP out of the range of the DHCP server.

**Comment by interdpth** [comment]
trying opening port 9295,9296

**Comment by carlosmax3D** [comment]
It's opened in the modem, I use my android to get into the PS4 over 4G network and it works.

**Comment by interdpth** [comment]
Alright, are you on 7.50? I am now able to connect to target but video stream is not working :/

**Comment by interdpth** [comment]
Here's my no video stream log
[chiaki_session_2020-05-04_14-07-00-740740.log](https://github.com/thestr4ng3r/chiaki/files/4576815/chiaki_session_2020-05-04_14-07-00-740740.log)

**Comment by carlosmax3D** [comment]
Yes, It have the latest update, I see your log, have you activate VAAPI support?. I been uncheck the VAAPI support because its not working on my Linux and neither on my Windows.  It said "avcodec_get_hw_config" as the issue 221

**Comment by TalaChartShiraz** [comment]
Could you find any solution @carlosmax3D?
I have the same issue!!!!

**Comment by carlosmax3D** [comment]
Go into the commits part, and the last commit, click con the green check, dive into appvoyeur and download the last artifact, it works for me on windows 10, I'm still trying to compile the project on my own to give a chance to enhance the capability to map the controller into a generic joystick
