### ISSUE TITLE
Hide Controller Overlay on Android [Feature Request]

### ISSUE THREAD

**Issue by catchthetide** [thestr4ng3r/chiaki#227]
**What platform does your feature request apply to?**
Android

**Is your feature request related to a problem? Please describe.**
It's frustrating to have the controller button overlay visible when I'm playing with a physical controller and don't need it.

**Describe the solution you'd like**
Please add an option either to remove the overlay or to make it 100% invisible via transparency settings.

**Describe alternatives you've considered**
It would be even better if the overlay automatically went invisible when a controller is detected!

**Additional context**
Thanks for your time and this wonderful app!

**Comment by SpartyYo** [comment]
I just swipe up from the bottom and there's a little panel that shows up that you can toggle the overlay on or off, as well as making a touch button

**Comment by thestr4ng3r** [comment]
Yep, this feature already exists:
![photo_2020-05-06_09-45-54](https://user-images.githubusercontent.com/1460997/81149397-6caab700-8f7e-11ea-8623-5b06767ac90d.jpg)
