### ISSUE TITLE
Switch version of Chiaki crashes Atmosphere (10.0)

### ISSUE THREAD

**Issue by Ry3yr** [thestr4ng3r/chiaki#230]
**Environment**

Firmware: 10.0.0 (Atmosphere 0.11.1-master-d81a3bdc)

**Describe the bug**

Error Code 2162-0002 (0x4a2)
Program.100000000000012

**To Reproduce**

Start /switch/Chiaki.nro via Homebrew menu of Switch

**Log Files**

n/A

**Screenshots**

n/A

**Additional context**

n/A

**Comment by thestr4ng3r** [comment]
Where did you get this nro from? There is no switch version of chiaki. (yet)

**Comment by Ry3yr** [comment]
That one
https://github.com/H0neyBadger/chiaki/releases/download/v0.0.4-switch/chiaki.nro

Am Mittwoch, 13. Mai 2020 schrieb Florian Märkl <notifications@github.com>:

**Comment by Ry3yr** [comment]
> Where did you get this nro from? There is no switch version of chiaki. (yet)

Is such thing in the works from your side then ?

**Comment by thestr4ng3r** [comment]
Ah I see, that does not come from me. However I am in contact with @H0neyBadger and the long-term plans are to merge it into this repository.

**Comment by Ry3yr** [comment]
Sweet, looking forward to it !

2020-05-13 20:37 GMT+02:00, Florian Märkl <notifications@github.com>:

**Comment by H0neyBadger** [comment]
Hello, 

@Ry3yr The switch version is not officially supported yet. But we are actually discussing this topic in https://gbatemp.net/threads/chiaki-ps4-remote-play-homebrew.564553/
logs are required to troubleshoot some problems. You will find many guidances in this forum. 

According to your latest description, that's an old issue. 
Could you please clear all chiaki.nro files from your SD card ?
Then use the latest build. 
Check carefully your config file location and content. 
Troubleshoot instructions are available in gbatemp.net. 
Be careful, logs should not be shared on public forum or place. 

Thank you @thestr4ng3r, should I open github issues on my fork to handle switch specific problem (temporary) ?

**Comment by thestr4ng3r** [comment]
> Thank you @thestr4ng3r, should I open github issues on my fork to handle switch specific problem (temporary) ?

Yes, as long as the code is there, that probably makes the most sense.

It would also be great if you could start splitting your changes into PRs to this repo now, probably best starting with the mbedtls port. I would be glad to review/merge them.

**Comment by Ry3yr** [comment]
Final note:
It was the missing chiaki.conf (which is sadly not supplied in the github version, and had to be fetched from a gbatemp post).

[chiaki.zip](https://github.com/thestr4ng3r/chiaki/files/4634285/chiaki.zip)

Now no more crashes seem to happen and I'm prompted for an input (as it should be).



I attached it here, for those that need it.

Thanks (both of you!)
