### ISSUE TITLE
need microphone support

### ISSUE THREAD

**Issue by independentcod** [thestr4ng3r/chiaki#231]
**What platform does your feature request apply to?**
Choose one or more: Desktop/Android/Both/...
arch linux laptop

**Is your feature request related to a problem? Please describe.**
Need microphone feature
**Describe the solution you'd like**
be able to talk in game
**Describe alternatives you've considered**
plugging my mic into controller
**Additional context**

**Comment by thestr4ng3r** [comment]
Duplicate of #52
