### ISSUE TITLE
cmake compile error

### ISSUE THREAD

**Issue by independentcod** [thestr4ng3r/chiaki#236]
**Environment**
 - OS/Distribution: archi linux
 - Desktop Environment: lxde
 - Hardware: intel hd 5500 lenovo laptop core i5
 - Exact Version or Commit Hash and Installation Method: as of today

**Describe the bug**
[100%] Linking CXX executable chiaki
/sbin/ld: /usr/local/lib/libavcodec.a(pngenc.o): undefined reference to symbol 'deflateInit2_'
/sbin/ld: /usr/lib/libz.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [gui/CMakeFiles/chiaki.dir/build.make:446: gui/chiaki] Error 1
make[1]: *** [CMakeFiles/Makefile2:392: gui/CMakeFiles/chiaki.dir/all] Error 2
make: *** [Makefile:183: all] Error 2

**To Reproduce**
execute cmake .

**Expected behavior**
compile success

Also I can't stop lagging while in game the screen starts tearing off

**Comment by thestr4ng3r** [comment]
`/usr/local/lib/libavcodec.a` seems wrong. The library you will want to use on Arch is `/usr/lib/libavcodec.so` which is part of the package `ffmpeg`.
Do you know where this `/usr/local/lib/libavcodec.a` comes from on your system? If it is part of a package, you can check which one it is by calling `pacman -Qo /usr/local/lib/libavcodec.a`.

**Comment by independentcod** [comment]
nevermind I will intall latest debian lets see how it goes there

**Comment by westonmyers** [comment]
If you're settled on not using AUR, at least look at the chiaki-git[chiaki-git](https://aur.archlinux.org/packages/chiaki-git/)  package over there as a point of reference regarding the dependencies. It build just fine for me, so you likely just don't have a dependency installed vs there being an issue with how a given library is packaged on Arch.

**Comment by thestr4ng3r** [comment]
> nevermind I will intall latest debian lets see how it goes there

Please don't. Arch >>>> Debian :-P

**Comment by independentcod** [comment]
Seems like it runs better on Xubuntu

**Comment by thestr4ng3r** [comment]
Closing because the issue was in the local environment.
