### ISSUE TITLE
VAAPI seems to be broken on WIndows

### ISSUE THREAD

**Issue by ya-boop** [thestr4ng3r/chiaki#247]
**Environment**
 - OS/Distribution: Windows 10 x64 2004  
 - Desktop Environment: (???) 
 - Hardware: i7 6700k, RX 480. second pc: fx 8320e, gtx 980
 - Exact Version or Commit Hash and Installation Method: version 1.2.1 from "release" page on github

**Describe the bug**
 avcodec_get_hw_config failed error appear when turning on VAAPI in options

**To Reproduce**
1. Go to 'settings'
2. Click on 'hardware deocode method.'
3. Scroll down to 'vaapi'
4. Try to connect to your PS4
5. error "Failed to initialize Stream Session: avcodec_get_hw_config failed" will appear 

**Expected behavior**
ability to use my gpu to decode stream 

**Log Files**
https://pastebin.com/2SUCGJaw

**Comment by Brainiarc7** [comment]
VAAPI works on Linux only.
For Windows, HWAccel is available typically via DXVA, NVDEC, QSV, etc based
on the available GPU.
