### ISSUE TITLE
Intermittent Controller Detection

### ISSUE THREAD

**Issue by crl0901** [thestr4ng3r/chiaki#287]
**Environment**
 - OS/Distribution: Linux Mint 20
 - Desktop Environment: Cinnamon 4.6.6
 - Hardware: Nvidia GeForce GTX 950
 - Exact Version or Commit Hash and Installation Method: Appimage 1.2.1

**Describe the bug**
Chiaki seems to intermittently fail to detect my wired Xbox 360 controller.  It seems to be random, as sometimes it works fine, and then other times, it does not, even after reboots of my PC and PS4.

**To Reproduce**
1. Exit Steam
2. Open Chiaki
3. Connect to PS4

**Expected behavior**
The controller should be recognized every time I connect.

**Log Files**
If your issue is about Registration or Streaming, you MUST attach a log file of a session that showed your issue here.
Do not enable Verbose Logging unless explicitly told to.
On desktop, you can see the directory that log files are written to in the Settings under "Log Directory".
On Android, go into Settings -> Session Logs and export one from there.

**Screenshots**

**Additional context**
I do have to exit Steam prior to using Chiaki as Steam seems to take control of the controller and Chiaki will not recognize it unless Steam is not running.  I mapped the controller in the Chiaki config file which I've attached.  I've also attached a log from a session where the controller is not being detected.
[chiaki_session_2020-07-24_08-45-50-259259.log](https://github.com/thestr4ng3r/chiaki/files/4971959/chiaki_session_2020-07-24_08-45-50-259259.log)

**Comment by crl0901** [comment]
Additional context update:  I left the PS4 alone for a few hours and it went into power saving mode.  In Chiaki, I sent a wake packet, then I connected to it and my controller now works.  I've attached a log from the working session.
[chiaki_session_2020-07-24_12-59-43-565565.log](https://github.com/thestr4ng3r/chiaki/files/4973317/chiaki_session_2020-07-24_12-59-43-565565.log)

**Comment by thestr4ng3r** [comment]
Please try again by building current master from source. (After Travis changed their Open Source plans, I can't supply AppImages for now)

**Comment by crl0901** [comment]
Building from the latest master seems to resolve the issue.
