### ISSUE TITLE
Chiaki is featured in my custom KALI LINUX ISO - MollyEskam-Linux

### ISSUE THREAD

**Issue by independentcod** [thestr4ng3r/chiaki#293]
https://gitlab.com/remigirard28/MollyEskam-Linux

The template below shows what you need to include in a good feature request, and you must use it.
I'm happy to help, but you have to ensure I fully understand what you want and have the information I need. -->

**What platform does your feature request apply to?**
Choose one or more: Desktop/Android/Both/... Debian

**Is your feature request related to a problem? Please describe.**
No need to compile its already compiled within the OS
**Describe the solution you'd like**
https://github.com/independentcod/MollyEskam-Linux

**Describe alternatives you've considered**

**Additional context**

**Comment by thestr4ng3r** [comment]
Nice, thanks for the info!
