### ISSUE TITLE
v1.0.0 source tarball is missing submodules contents

### ISSUE THREAD

**Issue by delroth** [thestr4ng3r/chiaki#3]
```
$ tar tf chiaki-1.0.0.tar.gz
...
chiaki-1.0.0/third-party/
chiaki-1.0.0/third-party/CMakeLists.txt
chiaki-1.0.0/third-party/gf-complete/
chiaki-1.0.0/third-party/jerasure/
chiaki-1.0.0/third-party/nanopb/
```

**Comment by thestr4ng3r** [comment]
Unfortunately that is just how GitHub creates these automatically, so I'm afraid we won't be able to fix this. Is there any reason you need a tarball specifically?

**Comment by delroth** [comment]
That's usually what distro packaging uses as primary source, so I expect other people will hit this (esp. since the third-party dependencies are not optional right now -- so the source tarball is unusable). I've personally switched my package to clone the git tag.

I thought it's possible to provide your own source tarball for releases instead of relying on the auto-generated one?

**Comment by thestr4ng3r** [comment]
Yes, I will add manually generating a tarball to Travis.
