### ISSUE TITLE
Please add motion sensor

### ISSUE THREAD

**Issue by WaitingKy** [thestr4ng3r/chiaki#300]
**What platform does your feature request apply to?**
Choose one or more: Desktop/Android/Both/...
Android
**Is your feature request related to a problem? Please describe.**
I can't play games like Heavy Rain or Detroit: Become Human because there is no motion sensor support.
**Describe the solution you'd like**
Please add motion sensor for Android version.
**Describe alternatives you've considered**

**Additional context**
I think you should focus on touchpad and motion sensor support so users can enjoy remote playing with full features.
Thank you, keep up amazing work!

**Comment by thestr4ng3r** [comment]
Thanks for reporting, but this is already tracked in #85
