### ISSUE TITLE
Accelerometer/gyroscope please

### ISSUE THREAD

**Issue by shingetsu00** [thestr4ng3r/chiaki#305]
**What platform does your feature request apply to?**
Choose one or more: Desktop

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when i can't play because i can't use motion sensor

**Describe the solution you'd like**
I would like the Accelerometer/gyroscope  to be implemented

**Comment by thestr4ng3r** [comment]
duplicate of #53
