### ISSUE TITLE
Performance Degradation from 1.0.2 to 1.0.3 on Linux

### ISSUE THREAD

**Issue by csfalcione** [thestr4ng3r/chiaki#32]
Tested the AppImages on Linux Mint 19.2 with a 6600K, GTX 1070 (with the 430 proprietary driver), and kernel 5.0.0. Used a wired DS4. In 1.0.3, there is a slight stutter upon every button press, but at least a second long freeze when the triggers are pressed. Also, the framerate seems to be lower overall. In 1.0.2, streaming is buttery smooth (but sadly lacking fullscreen and controller mapping fixes).

**Comment by thestr4ng3r** [comment]
Please run both versions with htop in parallel and check whether you notice any major difference regarding what thread uses how much resources:
![Bildschirmfoto vom 2019-09-22 19-28-44](https://user-images.githubusercontent.com/1460997/65391936-4e85a300-dd6f-11e9-9978-885b507c5f6e.png)
Also please post a log from each version.

**Comment by fpiesche** [comment]
I'm running into this as well, on Solus OS 4.0 on a late-2015 Macbook Air (i5 5250U, 8GB RAM, integrated Intel GPU). Using a DS4 connected to the PS4 (logged into Chiaki via an alternate account).

On 1.0.2, 720p60 is perfect, on 1.0.3 even 540p30 gives me at best about 10fps on display (but audio is 100% fine, no stutter or crackling). I'll take a htop snapshot of both versions in a later when I have some time to mess around with the whole thing some more

**Comment by fpiesche** [comment]
Here's 1.0.3:
[chiaki_session_1.0.3.log](https://github.com/thestr4ng3r/chiaki/files/3667595/chiaki_session_1.0.3.log)
![image](https://user-images.githubusercontent.com/393620/65835279-3caa7f80-e2dc-11e9-96a7-c3cda5c7b51a.png)

**Comment by fpiesche** [comment]
Here's 1.0.2:
[chiaki_session_1.0.2.log](https://github.com/thestr4ng3r/chiaki/files/3667602/chiaki_session_1.0.2.log)
![image](https://user-images.githubusercontent.com/393620/65835297-885d2900-e2dc-11e9-8c5f-1fa344e6abdf.png)

**Comment by fpiesche** [comment]
Resource use seems fairly even between the two, and I'm not seeing anything notably different between the logs either...

**Comment by thestr4ng3r** [comment]
Yeah both look reasonable. I will investigate further.

**Comment by fpiesche** [comment]
If you'd like me to run with verbose logging or dig around any other system stats, give me a shout and I'll be happy to help :)

**Comment by cassidyjames** [comment]
I’m also experiencing this on elementary OS 5.0 Juno. For me, both the PS4 and computer are on Wi-Fi. 1.0.2 works very well, with 720p 60fps working great. With 1.0.3 even 360p 30fps is a laggy, unusable affair (like 1fps). The difference is staggering. Happily using 1.0.2 for now. :)

**Comment by thestr4ng3r** [comment]
1.0.3 also had some changes in the build process of the AppImage. You could also try to build from source and compare. That might help us narrow down the issue.

**Comment by fpiesche** [comment]
Building from source does indeed work fine!

**Comment by alx242** [comment]
Anyone want to build a new Appimage that doesn't have the weird fps drop?

**Comment by thestr4ng3r** [comment]
@fpiesche @cassidyjames @csfalcione Please post the output of
```
cat "/proc/`pidof AppRun.wrapped`/maps"
```
for both versions while the stream is running.

**Comment by fpiesche** [comment]
I don't actually have an `AppRun.wrapped` for the 1.0.2 AppImage, but I've run the above for both of the processes that spawns for me. Here's the results for 1.0.2 and 1.0.3 AppImages and 1.0.3 compiled from source:
[chiaki-1.0.2.txt](https://github.com/thestr4ng3r/chiaki/files/3678525/chiaki-1.0.2.txt)
[chiaki-1.0.3-appimage.txt](https://github.com/thestr4ng3r/chiaki/files/3678526/chiaki-1.0.3-appimage.txt)
[chiaki-1.0.3-source.txt](https://github.com/thestr4ng3r/chiaki/files/3678527/chiaki-1.0.3-source.txt)

**Comment by thestr4ng3r** [comment]
Thanks!

**Comment by thestr4ng3r** [comment]
While I still cannot reproduce this, a lot has changed again in the build process, so I would like to ask you to test these AppImages:
https://transfer.sh/tU2sy/Chiaki-1045cfe27dd2066597f7cbbf119d8f46e6fcacd2-Linux-x86_64.AppImage (built from xenial)
https://transfer.sh/3Te4X/Chiaki-1045cfe27dd2066597f7cbbf119d8f46e6fcacd2-Linux-x86_64.AppImage (built from bionic)

**Comment by alx242** [comment]
Great and thanks, I will install and retry using the controller :)

**Comment by fpiesche** [comment]
The Xenial AppImage still shows the performance issues for me, but the Bionic one works fine!

**Comment by alx242** [comment]
Yeah the Bionic version works for me as well. The current v1.0.4 release has same problems as v1.0.3 had however, guess it wasn't build on Bionic.

**Comment by kiwidoggie** [comment]
Are there new builds available for bionic? (Link is dead) I am also getting around 5FPS in the app, yet alone being able to connect (typing is extremely slow and unresponsive)

**Comment by alx242** [comment]
> Are there new builds available for bionic? (Link is dead) I am also getting around 5FPS in the app, yet alone being able to connect (typing is extremely slow and unresponsive)
> 
> AppVersion: 1.0.4
> Ubuntu 18.04 LTS (fully up to date)
> AMD Threadripper 1950x
> AMD RX560
> 128GB RAM

I’ve actually haven’t had any problems with the new builds and my bionic machine... not sure why but I works great nowadays :)

**Comment by alx242** [comment]
Realised this was still a issue when I switched to a older kernel, 5.0 instead of 5.3. It worked by running Bionic build of the appImage but it looks like that the upload of those images has stopped working for a while:
```
$ if [ ! -z "$DEPLOY_FILE" ]; then curl -m 30 --upload-file "$DEPLOY_FILE" "https://transfer.sh/$DEPLOY_FILE"; echo; fi
curl: (28) Operation timed out after 30000 milliseconds with 0 bytes received
```

Can be seen here: https://travis-ci.com/thestr4ng3r/chiaki/jobs/258696816

Perhaps these builds could be shipped to github together with the other builds....or?

**Comment by seuffert** [comment]
ran into the same problem here. ubuntu 19.04, Kernel 5.3/5.4rc8 :( (Thinkpad T580) couldn't find a recent bionic appimage build to try

**Comment by thestr4ng3r** [comment]
Here is a more recent build: https://transfer.sh/51O9j/Chiaki-e3ea1e40b2d805d8dab5e3959ace5f9de304f873-Linux-x86_64.AppImage
I prefer not to ship it on GitHub releases since it's just a workaround. AppImages should generally be built on the lowest supported env.

**Comment by elvinasp** [comment]
> Here is a more recent build: https://transfer.sh/51O9j/Chiaki-e3ea1e40b2d805d8dab5e3959ace5f9de304f873-Linux-x86_64.AppImage

Issue #10 is shown as closed. However with the build above, when I tried to connect after PS4 powerdown, I saw exactly the same behavior. I was not able to connect to PS4 until I disconnected PS4 controler from PC, pushed my PIN code and then reconnected controller via USB to PC. Is this some earlier branch?

**Comment by thestr4ng3r** [comment]
I think I was able to fix it. Someone who can reproduce the issue with the 1.1.3 release, please try this build: https://oshi.at/FttUjr
By the way, you can now also verify the hash of the builds from travis if you don't trust these upload services: https://travis-ci.com/thestr4ng3r/chiaki/jobs/281171063#L3311

**Comment by Arnvidr** [comment]
1.1.3 lagged almost too much to use the main menu, on this latest one I could almost play Trackmania!

**Comment by csfalcione** [comment]
Same. 1.1.3 was laggy and unplayable. That build was buttery-smooth. Good work :)

**Comment by jarrheyd** [comment]
@thestr4ng3r I wanted to try out the latest builds found in Travis, but the oshi links aren't working (I checked the logs), even when you've set the expiry to 90 days

**Comment by rmarfil3** [comment]
@thestr4ng3r  I wanted to try out the latest builds found in Travis, but the oshi links aren't working (I checked the logs), even when you've set the expiry to 90 days

**Comment by thestr4ng3r** [comment]
New release is published.
