### ISSUE TITLE
8.00 firmware 

### ISSUE THREAD

**Issue by darwpm4gs** [thestr4ng3r/chiaki#328]
**Environment**
ANY
**Describe the bug**
 sony changed encryption for remote play
so it's not possible to use chiaki with 8.00+ firmware

**Comment by mlabarca** [comment]
Yeah having the same issue as well, but is there even a way around this?

**Comment by krijt** [comment]
No, I recon it just needs to be patched. 

this is from twitter:
> Florian Märkl
>@thestr4ng3r
>PSA: If you rely on Chiaki, do not update to PS4 Firmware 8.0 just yet, since it is currently incompatible. I am working on the >update (no eta).

**Comment by aassaf869** [comment]
Damn, just wanted to hop on a game of Rocket League from my laptop on the PS4...
This sucks.

**Comment by Fuzzi99** [comment]
Damn it my ps4 updated automatically, was wondering why it was throwing a version mismatch error when trying to use it today

**Comment by genyg** [comment]
good afternoon. When will you fix it?

**Comment by krijt** [comment]
there is no ETA given.

**Comment by genyg** [comment]
please hurry up thestr4ng3r. We wait :(

**Comment by TheRogueGrunt** [comment]
Gotta love random firmware updates that seem to do nothing but break 3rd party apps

**Comment by darthHunterous** [comment]
> Gotta love random firmware updates that seem to do nothing but break 3rd party apps

I doubt it's "random". They changed the official app a lot (finally it is working again on my Mac lol), possibly to support he PS5's remote play feature.

**Comment by edbergcoelho** [comment]
Awww :( just found out about this app, was looking forward to test it out, it looks great! Well, lets wait then. From what ive seen, its a incredible work. Congratulations!

**Comment by wverdier** [comment]
I tried to use Sony's Remote Play windows application see if I could find anything interesting by looking at the packet that is sent with the regist request. The official application connects fine with the "automatic" method, but it can't connect when I use the "manual" linking method with the PIN. As far as I understand this manual method is the one that should actually send a regist request, I don't care much about the automatic linking working or not.

Can anyone else at least connect with a PIN on the new official application (Other Connections -> PS4 -> Link Manually) with a 8.00 firmware ?

**Comment by tolysz** [comment]
Replacing using `RP-Version: 10.0` will fail with 
```
[E] Reported Application Reason: 0x80108bff (unknown)
```

**Comment by davewasthere** [comment]
> I tried to use Sony's Remote Play windows application see if I could find anything interesting by looking at the packet that is sent with the regist request. The official application connects fine with the "automatic" method, but it can't connect when I use the "manual" linking method with the PIN. As far as I understand this manual method is the one that should actually send a regist request, I don't care much about the automatic linking working or not.
> 
> Can anyone else at least connect with a PIN on the latest version of the official application (Other Connections -> PS4 -> Link Manually) with a 8.00 firmware ?

Yep. Managed to connect with PIN with v8 firmware no worries (with official client)

**Comment by thestr4ng3r** [comment]
> Replacing using `RP-Version: 10.0` will fail with
> 
> ```
> [E] Reported Application Reason: 0x80108bff (unknown)
> ```

Yeah it's more than just a version bump. Updated version is live now, have fun!

**Comment by genyg** [comment]
can anyone tell me how to use the mouse in Chiaki??? IN MAC OSX?

**Comment by genyg** [comment]
Make mouse support please thestr4ng3r
