### ISSUE TITLE
pin?

### ISSUE THREAD

**Issue by johnn623** [thestr4ng3r/chiaki#33]
When I register my ps4 to Chiaki, it asks for a pin. Where do I find this pin?

**Comment by Marco01809** [comment]
You have to go to Settings -> Remote Play -> Add Device on your PS4. The pin is displayed on the screen.

When connecting to the PS4 afterwards, it will also ask for the login pin for your PS4 profile (if you have set a pin).

**Comment by thestr4ng3r** [comment]
correct
