### ISSUE TITLE
Please can this be made to work on Raspberry Pi 4!?

### ISSUE THREAD

**Issue by Fredrum** [thestr4ng3r/chiaki#331]
Hello!

This looks super cool and I'd love to be able to use it with my small Raspberry
setup. Please please could you guys consider trying to make this buildable for Rpi4?
The rpi has hardware decoding build in so that might be helpful.

**What platform does your feature request apply to?**
RPi4 + Raspbian

**Is your feature request related to a problem? Please describe.**
I want to be able to stream my PS4 games to my minimal raspberry client.

**Describe the solution you'd like**

Can there be a mode that can build this on 32 bit Raspbian?

I think the current issue is OpenGL but this being purely a streaming piece of software I hope lowering the OpenGL version demands might be ok.

**Comment by thestr4ng3r** [comment]
please check #126
