### ISSUE TITLE
Sound problem (only 24bit 48000Hz supported?)

### ISSUE THREAD

**Issue by wpinacz** [thestr4ng3r/chiaki#332]
**Environment**
 - OS/Distribution: Ubuntu 20.04 / Windows 10
 - Desktop Environment: Gnome 3.36 / Windows
 - Hardware: AMD Ryzen 5 3400G with Radeon Vega
 - Exact Version or Commit Hash and Installation Method: v1.2.1 build from sources (Ubuntu) / 1.2.1 (Windows)

**Describe the bug**
I've noticed that Chiaki uses only 24bit 48000Hz stereo sound. When on Ubuntu running from Appimage sound is fine, I wanted to run with VAAPI driver without success from Appimage, builded app from source gives me VAAPI but with error about sound: "**E] Audio Format with 2 channels @ 48000 Hz not supported by Audio Device**", same issue is on Windows using wireless headphones that support only 16bit 44100Hz sound

**To Reproduce**
1. Run Chiaki
2. Connect to PS4
3. No sound produced

**Expected behavior**
Sound should play with other sound settings (eg. 16bit 44100Hz, 32bit 48000Hz, stereo, mono, 5.1 etc...)

**Log Files**
[chiaki_session_2020-10-18_10-30-50-327327.log](https://github.com/thestr4ng3r/chiaki/files/5397230/chiaki_session_2020-10-18_10-30-50-327327.log)

**Comment by Kiiro-Yakumo** [comment]
Hmm...
This doesn't sound by the error given that it's Chiaki's fault per se. Check what sound card - or "sound card" - you have. It may be just that you have probably integrated thing that can't go beyond 16bit 44100 Hz or whatever.

**Comment by thestr4ng3r** [comment]
The reason why it only uses 16bit 48000Hz (not 24bit) is that this is the audio format that is begin sent from the PS4. This is then just put in a standard `QAudioOutput` which is supposed to handle resampling somewhere else.

I am curious about your audio hardware, could you please describe in detail what you are using? For example post the output of `pacmd info` on Linux if you use PulseAudio.

Since you are already building from source, you can also try to just remove this line here and see what happens: https://github.com/thestr4ng3r/chiaki/blob/master/gui/src/streamsession.cpp#L273

**Comment by wpinacz** [comment]
> Hmm...
> This doesn't sound by the error given that it's Chiaki's fault per se. Check what sound card - or "sound card" - you have. It may be just that you have probably integrated thing that can't go beyond 16bit 44100 Hz or whatever.

Integrated into motherboard:
Generic_1 [HD-Audio Generic], urządzenie 0: ALC887-VD Analog [ALC887-VD Analog]

**Comment by wpinacz** [comment]
> I am curious about your audio hardware, could you please describe in detail what you are using? For example post the output of `pacmd info` on Linux if you use PulseAudio.

Here's the output log:
[soundinfo.txt](https://github.com/thestr4ng3r/chiaki/files/5397957/soundinfo.txt)

**Comment by wpinacz** [comment]
Just to be clear: I don't care if it'll be 16/24/32 bit or 44100/48000Hz, I'm no audiophile and don't have super HiFi sound system, anything above 16bit 44100Hz is going to be irrelevant to me and my speakers ;)

**Comment by wpinacz** [comment]
> Since you are already building from source, you can also try to just remove this line here and see what happens: https://github.com/thestr4ng3r/chiaki/blob/master/gui/src/streamsession.cpp#L273

This does nothing....

**Comment by wpinacz** [comment]
Strange, if I run Appimage version then in log there's info about soundcard:
**Audio Device alsa_output.pci-0000_08_00.6.analog-surround-51 opened with 2 channels @ 48000 Hz, buffer size 15680**
When i run compiled version there's no info about soundcard, as if sound card don't detected.

**Comment by thestr4ng3r** [comment]
Maybe you are missing the `libqt5multimedia5-plugins` package then. The AppImage comes with its own libraries.

**Comment by wpinacz** [comment]
> Maybe you are missing the `libqt5multimedia5-plugins` package then. The AppImage comes with its own libraries.

Yes, they were missing, audio now works oob. Thank's thestr4ng3r !
