### ISSUE TITLE
Build error - libudev

### ISSUE THREAD

**Issue by testbughub** [thestr4ng3r/chiaki#337]
**Environment**
 - OS/Distribution: Linux Mint 19.3 Tricia
 - Desktop Environment: Cinnamon (X)
 - Hardware: Radeon HD 7500M 
 - Exact Version or Commit Hash and Installation Method: 702d31e 

**Describe the bug**
I'm following the steps in platform-build.md. I believe I've installed everything that I need.

**To Reproduce**
I'm clueless when it comes to building/compiling, so I'm not really sure.

**Expected behavior**
Well, an output without errors would be nice ^^ 

**Log Files**
~~~~~~~~~~~~
--   Found libudev, version 237
CMake Error at setsu/cmake/FindUdev.cmake:11 (target_link_libraries):
  Cannot specify link libraries for target "Udev::libudev" which is not built
  by this project.
Call Stack (most recent call first):
  CMakeLists.txt:74 (find_package)
~~~~~~~~~~~~
I hope that this explains what went wrong. If not, I can submit the entire log.

**Additional context**
As I mentioned, I'm a real newbie when it comes to building/compiling.
I also tried everything mentioned here: https://github.com/thestr4ng3r/chiaki/issues/191
If I've just missed something, I apologize!

**Comment by thestr4ng3r** [comment]
Try passing `-DCHIAKI_ENABLE_SETSU=OFF` to cmake.

**Comment by testbughub** [comment]
That takes care of that error (gives me another error about not finding ffmpeg libraries instead), but doesn't it need to be "ON" for the touchpad to work?
That was kinda the reason for me wanting to build it myself.

**Comment by tolysz** [comment]
https://installlion.com/linuxmint/tricia/upstream/l/libudev-dev/install/index.html

**Comment by testbughub** [comment]
> https://installlion.com/linuxmint/tricia/upstream/l/libudev-dev/install/index.html

I'm not getting anything. Doesn't look like it has instructions for Tricia>.

**Comment by thestr4ng3r** [comment]
Yes, setsu needs to be enabled if you want touchpad. I think libudev-dev is already installed since pkg-config is able to find it.
This seems more like an issue with old cmake, I have to check how to fix it.

**Comment by testbughub** [comment]
Yep, libudev-dev (237-3ubuntu10.42) is installed. 
And cmake (3.10.2-1ubuntu2.18.04.1).

**Comment by thestr4ng3r** [comment]
Try again now with `-DCHIAKI_ENABLE_SETSU=ON`. If you encounter more ffmpeg errors, update ffmpeg to >=4, for example from a ppa.

**Comment by testbughub** [comment]
I updated ffmpeg through jonathonf-ffmpeg-4 ppa, but I get some sort of version error (i think) for avcodec/avutil:
~~~~
-- Checking for module 'libavutil'
--   Found libavutil, version 56.51.100
-- Checking for module 'libswresample'
--   Found libswresample, version 3.7.100
-- Checking for module 'libswscale'
--   Found libswscale, version 5.7.100
-- Checking for module 'libavcodec'
--   Found libavcodec, version 58.91.100
-- Found FFMPEG: avcodec;avutil (found version "56.51.100") found components:  avcodec avutil 
~~~~

I may have messed up some packages when trying to fix this myself.

Sorry for just throwing errors at you. I don't like doing it, and if you don't believe it's necessary for the majority, I can live without the touchpad.

**Comment by thestr4ng3r** [comment]
There is no error in this output. Anything specifically that doesn't work?

**Comment by testbughub** [comment]
Oh, heh my bad. I'll just give you the whole thing instead.
~~~~
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.9", minimum required is "3") 
CMake Error at third-party/CMakeLists.txt:8 (add_subdirectory):
  The source directory

    /home/username/Downloads/chiaki/third-party/nanopb

  does not contain a CMakeLists.txt file.


-- Found Opus: /usr/include  
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.1.1") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'libudev'
--   Found libudev, version 237
-- Checking for module 'libevdev'
--   Found libevdev, version 1.5.8
-- Found Udev: udev (found version "237") 
-- Found Evdev: evdev (found version "1.5.8") 
-- Setsu enabled
-- Found SDL2: /usr/lib/x86_64-linux-gnu/cmake/SDL2/sdl2-config.cmake  
-- Checking for module 'libavutil'
--   Found libavutil, version 56.51.100
-- Checking for module 'libswresample'
--   Found libswresample, version 3.7.100
-- Checking for module 'libswscale'
--   Found libswscale, version 5.7.100
-- Checking for module 'libavcodec'
--   Found libavcodec, version 58.91.100
-- Found FFMPEG: avcodec;avutil (found version "56.51.100") found components:  avcodec avutil 
-- Configuring incomplete, errors occurred!
See also "/home/username/Downloads/chiaki/build/CMakeFiles/CMakeOutput.log".
See also "/home/username/Downloads/chiaki/build/CMakeFiles/CMakeError.log".
~~~~
