### ISSUE TITLE
Usage of param "morning" unclear

### ISSUE THREAD

**Issue by tuximail** [thestr4ng3r/chiaki#345]
**Environment**
 - OS/Distribution: Xubuntu
 - Desktop Environment: Xfce
 - Hardware: GeForce GT 1030, vulkan
 - Exact Version or Commit Hash and Installation Method: AppImage, latest version

**Describe the bug**
I am not able to connect directly to my playstation from cli as I am not aware what the "morning" parameter is for.

**To Reproduce**
1. Execute from cli:
``` bash
./Chiaki-v1.3.0-Linux-x86_64.AppImage --registkey ABCDEFGH --morning Q1VTQTEzMTUyCg== stream 192.168.178.24
```
2. Receive "Given morning has invalid size (expected 16, got 10)"

Where in this scenario _morning_ is the base64 encode ID-Code of a game from my ps4 (this is just a guess, because as explained - I have no clue what to put here for real).

**Expected behavior**
Start chiaki and connect to a previously registered device with the ID passed with _registkey_ running on the IP passed as last param.

**Log Files**
[2020-10-21 16:18:08:826826] [I] Chiaki Version 1.3.0
[2020-10-21 16:18:08:891891] [I] Starting session request
[2020-10-21 16:18:08:896896] [I] OpenGL initialized with version "4.6 (Core Profile) Mesa 20.2.1"
[2020-10-21 16:18:08:896896] [I] Trying to request session from PS4-xxxxxx
[2020-10-21 16:18:08:898898] [I] Connected to PS4-xxxxxx
[2020-10-21 16:18:08:898898] [I] Sending session request
[2020-10-21 16:18:08:902902] [E] Reported Application Reason: 0x80108bff (unknown)
[2020-10-21 16:18:08:902902] [I] Session has quit

**Additional context**
I tried multiple things to pass for this param, like the encoded ps4 hostname, etc.

**Comment by thestr4ng3r** [comment]
registkey and morning are the private keys you get from registration. The CLI is currently unaware of the consoles you have registered and saved so you have to pass this manually. You can determine your values like this:
```
> grep 'rp_.*key=' ~/.config/Chiaki/Chiaki.conf
1\rp_key=@ByteArray(\x13\x37...)
1\rp_regist_key=@ByteArray(abcdefgh\0\0\0\0\0\0\0\0)
```
Where rp_key is morning (take the stuff in `@ByteArray()` and turn it into base64) and rp_regist_key is registkey (just take `abcdefgh` here).

**Comment by tuximail** [comment]
Thanks for the explanation. However I am still having trouble. If I take everything between the brackets in the first line and convert it like this:
``` bash
echo '\xae\xb1[)\xb1...' | base64
```
and pass it to chiaki I still end up with:
`Given morning has invalid size (expected 16, got 17)`
Please note that I explicitly used single quotes to escape all the special characters in the string. Also note that there is a closing bracket within the string itself. I also tried to convert the bytecode to string with `xxd` and echoed the string with manual escaping of the special characters. But unfortunatelly no success....

**Comment by thestr4ng3r** [comment]
Try printf instead of echo.

**Comment by tuximail** [comment]
Thanks man - could have thought of this myself. Has been 10 years since my last touch with C-Software...

It works now. So here is a snippet that might be useful for other users:
``` bash
printf $(grep 'rp_key=' ~/.config/Chiaki/Chiaki.conf | sed -e 's/^.*ByteArray(//' -e 's/..$//') | base64
```
Maybe you could add the information to the readme or even better to the --help page. It would clear things up I guess :)

**Comment by thestr4ng3r** [comment]
Nice, feel free to send a PR if you want to enhance it.
