### ISSUE TITLE
Update F-Droid version

### ISSUE THREAD

**Issue by crisalis2** [thestr4ng3r/chiaki#362]
**What platform does your feature request apply to?**
Android.

**Is your feature request related to a problem? Please describe.**
F-Droid is still on 1.2.1, which doesn't work with the current PS4 firmware, and it's been 18 days since the fixed 1.3.0 version is out here.

**Describe the solution you'd like**
There's an updated F-Droid version.

**Additional context**
I'm not sure if I should open an issue here or in one of F-Droid's Gitlab repositories, but in that case there are many of them and I have no idea which would be the appropriate one. So opening an issue here seemed like the easiest option. For the next time that a situation like this (a critical update is delayed) may happen, please let me know if there's a better way or place for me to make F-Droid aware there's a Chiaki update.

**Comment by thestr4ng3r** [comment]
You can make a merge request to their repository updating this file: https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.metallic.chiaki.yml

**Comment by thestr4ng3r** [comment]
Actually, I just saw the metadata there is already updated. I can't really say why the build is not yet live, maybe it just takes a bit of time. But if it doesn't appear, it is an issue on their side.
