### ISSUE TITLE
Takion received data with unexpected data type 0x7

### ISSUE THREAD

**Issue by leo-lb** [thestr4ng3r/chiaki#373]
**Environment**
 - OS/Distribution:  Fedora 33 fully up to date as of now
 - Desktop Environment:  GNOME on Wayland 3.38.1
 - Hardware:  Dell XPS 13 2020 with Intel® Core™ i7-1065G7 and i915 driver
 - Exact Version or Commit Hash and Installation Method:  ea79836f0f40a8cc401768933137964c603dd3c5 compiled from source

**Describe the bug**

When playing Fall Guys - Ultimate Knockout I some times get these in stdout:

```
[W] Takion received data with unexpected data type 0x7
[W] offset 0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f  0123456789abcdef
[W]      0 00 25 a7 95 75 8e 77 c0 40 06 99 b1 e0 00 01 00 .%..u.w.@.......
[W]     10 10 2b 1d 31 37 00 00 00 00 07 00 42 00          .+.17......B.   
[W] Takion received data with unexpected data type 0x7
[W] offset 0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f  0123456789abcdef
[W]      0 00 25 a7 95 75 2c 9c ed f8 06 99 f0 c0 00 01 00 .%..u,..........
[W]     10 10 2b 1d 31 38 00 00 00 00 07 00 32 00          .+.18......2.   
[W] Takion received data with unexpected data type 0x7
[W] offset 0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f  0123456789abcdef
[W]      0 00 25 a7 95 75 53 5b 27 df 06 9a 24 50 00 01 00 .%..uS['...$P...
[W]     10 10 2b 1d 31 39 00 00 00 00 07 00 21 00          .+.19......!.   
[W] Takion received data with unexpected data type 0x7
[W] offset 0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f  0123456789abcdef
[W]      0 00 25 a7 95 75 59 e9 ef 63 06 9a 53 c0 00 01 00 .%..uY..c..S....
[W]     10 10 2b 1d 31 3a 00 00 00 00 07 00 10 00          .+.1:........   
[W] Takion received data with unexpected data type 0x7
[W] offset 0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f  0123456789abcdef
[W]      0 00 25 a7 95 75 67 be ff 02 06 9a 86 90 00 01 00 .%..ug..........
[W]     10 10 2b 1d 31 3b 00 00 00 00 07 00 00 00          .+.1;........   
```

It does not cause noticeable bugs but thought might be good to report still.
I am not sure if it's related to resolution and frame rate but I am playing at 720p 30fps. I also use a PS4 Controller via Bluetooth.
I do not know if it's specific to a game in particular.

**Comment by thestr4ng3r** [comment]
These might just be rumble packets, which are not yet supported. Does it happen whenever the controller normally would vibrate?

**Comment by leo-lb** [comment]
@thestr4ng3r That is likely, yes! Didn't think of it!

**Comment by thestr4ng3r** [comment]
Let's track this under #17 then.
