### ISSUE TITLE
Support for Non-Xperia Android Devices

### ISSUE THREAD

**Issue by theMalapeno** [thestr4ng3r/chiaki#39]
Would it be possible to port this project to non Sony Xperia Android devices?

I know some outdated and unsupported APKs exist plus there are paid for apps but having an open source code base that I can be sure there is no funny business going on would be amazing.

**Comment by thestr4ng3r** [comment]
yes

**Comment by proditaki** [comment]
I see you already are pushing Android commits.
Can we already compile and test for android?

**Comment by thestr4ng3r** [comment]
You can try it if you want. Just open the `android` directory in Android Studio and build it. But it is still very raw, currently you have to extract the keys from registration out of regular Chiaki and enter them manually to connect.

**Comment by theMalapeno** [comment]
OK awesome, so I guess I need to run through the registration process on a Linux based OS for example, then copy the keys over to the Android file system for Chiaki to utilise them.

Thanks guys, I'll give this a shot and see how it goes. Would it be much work for the Android version to derive the login keys itself?

**Comment by thestr4ng3r** [comment]
Not much work, only the GUI has to be built and a few JNI bindings have to be implemented.

**Comment by proditaki** [comment]
Very nice

**Comment by Gh0stWires** [comment]
What jni bindings have to be implemented? Wouldn't mind taking a crack at it.

**Comment by sambow23** [comment]
Have the app running on my Note 3 running Android 10, what does it mean by `Morning (base64)` when manually adding a console?

**Comment by thestr4ng3r** [comment]
It's part of the registration credentials/key that you would have to extract from the desktop client for now.

**Comment by theMalapeno** [comment]
That's pretty strange timing; just announced this week that Sony has added remote play for Android 5.0 and above for select PS4 games:

https://blog.us.playstation.com/2019/10/06/ps4-system-software-update-7-00-launches-this-week/

Not sure exactly what "select PS4 titles" includes.

**Comment by proditaki** [comment]
Keep in mind that the sony remote play app is far from optimized and it only supports controller for android 10

**Comment by thw0rted** [comment]
The Android version works great, I assume it's safe to close this issue.
