### ISSUE TITLE
Switch Port - Lag, Glitch or Ps4 not available

### ISSUE THREAD

**Issue by NathanIfinity** [thestr4ng3r/chiaki#405]
**Environment**
 - OS/Distribution:  Switch, SXOS 3.1, FW 10.2.0 
 - Desktop Environment:  N/A 
 - Hardware: Switch 
 - Exact Version or Commit Hash and Installation Method: ChiakiPS4RemotePlay_05D318B976B70000.nsp from: https://gbatemp.net/threads/chiaki-ps4-remote-play-homebrew.564553/

**Describe the bug**
Glitch, lags and randomly doesn't see my ps4 anymore, been using over a month with no issue, started yesterday and are constant, tried removing from switch, resetting config, re-installing, same issue, and now it randomly stops seeing my ps4.

**To Reproduce**
1. Lauch Chiaki on Switch
2. if Ps4 is recognized, connect 
3. move around in game and the game glitches
4. if I look at the game on the actual pS4 it's fine.

**Expected behavior**
No glitch since happened all of a sudden.

**Log Files**
Not sure how to provide those on switch version

**Screenshots**
I have a video of the issue.. see below

**Additional context**
N/a

https://user-images.githubusercontent.com/75090696/102834717-d6b78580-43c2-11eb-9ca7-f6e04866ba8b.mov

**Comment by thestr4ng3r** [comment]
SXOS is not supported, sorry. If you can experience the same issues on Atmosphère, feel free to create a new issue.
