### ISSUE TITLE
D-pad and L1 + R1 issues

### ISSUE THREAD

**Issue by DarkUmbre** [thestr4ng3r/chiaki#41]
After testing I believe I finally figured out the D-pad issue when I'm playing CTR I noticed when holding both L1 + R1 the client does not play well with the d-pad when doing drifting in the game. Sometimes after pressing both L1 + R1 the D-pad may act like you're for example hold down left or holding down right when you're not. I have noticed this problem on Linux and windows as well. So far this method is the easiest way to trigger the glitch I have noticed. My current OS running the chiaki client is Manjaro.

**Comment by thestr4ng3r** [comment]
I think it is fixed now, can you build from source and test it with current master?

**Comment by DarkUmbre** [comment]
I tested it out, pressed the buttons I did before to trigger the problem and seems to all be good now!

**Comment by thestr4ng3r** [comment]
Nice, thanks for testing!
