### ISSUE TITLE
How to build without third-party source

### ISSUE THREAD

**Issue by Odelpasso** [thestr4ng3r/chiaki#44]
Hello,

I try to create an ebuild for Gentoo but i need to use the source tarball where the 3rd-party source (for gf-complete, jerasure and nanopb) are not available.

I can install these application/librairies on Gentoo like they'are available in the official repo.
Unfortunatly, i have error during compilation/build because files and these 3rd-party are missing.

How i can build Chiaki like i want ?

Thanks

**Comment by thestr4ng3r** [comment]
This needs some adjustments in the build system.

The way to do this would be to add options called `CHIAKI_USE_SYSTEM_JERASURE`, etc. around here: https://github.com/thestr4ng3r/chiaki/blob/88db8c884094ba00da2224b444020b1752ef6b83/CMakeLists.txt#L6
Then write a find module for each library and put them into https://github.com/thestr4ng3r/chiaki/tree/master/cmake
The find modules should create import targets, not just variables.
Then wrap the respective blocks here in if-statements: https://github.com/thestr4ng3r/chiaki/blob/master/third-party/CMakeLists.txt and if the system version should be used, call `find_package()` and make the targets like `gf_complete` an alias for the imported one.

I have many more issues to resolve right now, so if you want this fast, feel free to send a pr.

**Comment by thestr4ng3r** [comment]
Options for using jerasure, gf-complete and nanopb from the system are now available. By default, the build system will first search for the system libraries and fall back to the submodules. If you want to force it to only use system libraries, you can pass `-DCHIAKI_USE_SYSTEM_JERASURE=ON -DCHIAKI_USE_SYSTEM_NANOPB=ON` to cmake, which will make it error if it doesn't find the libs and never use the submodules.
Let me know if you need anything else.
