### ISSUE TITLE
Android 7.0 support

### ISSUE THREAD

**Issue by xhable1337** [thestr4ng3r/chiaki#48]
Hello! I have a device with Android 7.0 Nougat. As I can see, there are some Android commits in the repo, so I decided to try to build it.
But while building, an error has occurred: 

> The application's minSdkVersion is newer than the device API level.

My next step was to decrease `minSdkVersion` in `android/app/build.gradle` from 26 to 24, the build was completed successfully, but the app on the phone was not launching (white screen for a second, then quit).
Also, I know that the Android port is now in development and builds are raw, so I want to ask you. Will Android 7.0 _(SDK v.24)_ be supported by the app?

**Comment by thestr4ng3r** [comment]
For now I have only been testing on Android 10, but the minimum version can probably be set lower later since I don't use any features that require it afaik. For your issue, check the Logcat for the error.

**Comment by proditaki** [comment]
Im getting "protoc not found" when compiling
