### ISSUE TITLE
Linux Dualshock 4 mapping is wrong

### ISSUE THREAD

**Issue by SavnoorSamra** [thestr4ng3r/chiaki#5]
The square and triangle buttons are switched around on my Linux machine. this is a minor problem and I hope it can be fixed soon!

**Comment by AstraAsura** [comment]
you can try to fix this in your ps4 system ... the lastest version allow you to switch the button

**Comment by thestr4ng3r** [comment]
What kind of controller do you use? A regular Dualshock 4? Mapping is generally done by SDL GameController, it can be adjusted with that. But it could also be that the mapping inside Chiaki is wrong, I will check that.

**Comment by SavnoorSamra** [comment]
I use a regular Dualshock 4 and the mapping changer on the ps4 itself doesn't seem to work. And mapping is fine on other Linux games and parsec so it's most likely in chiaki

**Comment by SJBERTRAND** [comment]
I have the same problem here. It does the same thing with a DS4,a Xbox Controller and a XBOX 1 controller. I also tried two different Linux machines with the appimage and a compile version. Always the same result Square and the triangle are inverted

**Comment by SJBERTRAND** [comment]
Hey I know you close the thread but just to let you know if I open Chiaki with the console I can hit any button any the console is quiet but when click the triangle I get this

[W] Takion received data with unexpected data type 0x7
[W] offset 0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f  0123456789abcdef
[W]      0 00 0c ce 6f be dd 04 df 2c 01 3c 0c 70 00 01 00 ...o....,.<.p...iaki
[W]     10 10 3b cb cb 60 00 00 00 00 07 00 00 00          .;..`........ 

I change the mapping in /chiaki/lib/include/chiaki/controller.h before recompiling and still get the same Issue. Im running Arch right now I'll switch to Ubuntu and try again. You might not care but I'll keep you posted.
Awesome work by the way.
