### ISSUE TITLE
Sony killed Chiaki with 7.00 update

### ISSUE THREAD

**Issue by DarkUmbre** [thestr4ng3r/chiaki#51]
I get an connect error as of the latest update
```
[I] Regist starting search
[I] Regist sending search packet
[I] Regist received search response from (My ps4 ip address sorry I don't like sharing my ps4's ip)
[I] Regist connected to (My ps4 ip address), sending request
[I] Regist waiting for response
[E] Regist received HTTP code 403
[E] Reported Application Reason: 0x80108bff (unknown)
[E] Regist eventually failed
```

**Comment by Marco01809** [comment]
Confirmed, but reason is slightly different for me:
```
[2019-10-08 17:39:45:828828] [E] Reported Application Reason: 0x80108b11 (unknown)
```

**Comment by thestr4ng3r** [comment]
Streaming is fixed in source now if you have registered the console before. I'm currently investigating the registration.

**Comment by sdipede** [comment]
Any luck resolving registration? Just found Chiaki yesterday to use Remote Play on Linux!

**Comment by thestr4ng3r** [comment]
Yes, just fixed registration locally, so expect it soon.

**Comment by thestr4ng3r** [comment]
Registration now works again.
However for 7.0 you will need your PSN Account ID as opposed to the Online ID that was used before which was just the username. I have been extracting this ID from the Windows Client using Frida for now, but I am sure there will be easier ways to get it.
For the ones who know how to use it, here is the Frida script I have been using which prints the id when a manual registration is performed: 
[main.ts.gz](https://github.com/thestr4ng3r/chiaki/files/3708669/main.ts.gz)

**Comment by Technifocal** [comment]
So just to confirm as of current the only way to acquire my account ID is via MITMing the official clients? I don't have the official Windows version set up so I was hoping there'd be an easier way directly with Linux.

**Comment by thestr4ng3r** [comment]
As said, it is very likely there are easier ways to obtain it. This is just the only known one for now.

**Comment by thestr4ng3r** [comment]
A script for easily obtaining the ID is now provided: https://github.com/thestr4ng3r/chiaki/blob/master/scripts/psn-account-id.py

**Comment by Technifocal** [comment]
I just tried this and am still receiving an error (403 http). Can I confirm I am meant to be using the base64 output (`This is your AccountID:`) and not the `user_id` from the JSON?

**Comment by thestr4ng3r** [comment]
Yes. Post the verbose log output of your registration (only if it fails).

**Comment by hyu9a** [comment]
I got my account ID using the script but registration still fails, here is the chiaki console log

[I] Regist starting search
[I] Regist sending search packet
[V] Regist received packet:
[V] offset 0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f  0123456789abcdef
[V]      0 52 45 53 32 01 05 00                            RES2...         
[I] Regist received search response from 192.168.1.67
[I] Regist connected to 192.168.1.67, sending request
[I] Regist waiting for response
[V] Regist response HTTP header:
[V] offset 0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f  0123456789abcdef
[V]      0 48 54 54 50 2f 31 2e 31 20 34 30 33 20 46 6f 72 HTTP/1.1.403.For
[V]     10 62 69 64 64 65 6e 0d 0a 43 6f 6e 6e 65 63 74 69 bidden..Connecti
[V]     20 6f 6e 3a 20 63 6c 6f 73 65 0d 0a 50 72 61 67 6d on:.close..Pragm
[V]     30 61 3a 20 6e 6f 2d 63 61 63 68 65 0d 0a 43 6f 6e a:.no-cache..Con
[V]     40 74 65 6e 74 2d 4c 65 6e 67 74 68 3a 20 30 0d 0a tent-Length:.0..
[V]     50 52 50 2d 56 65 72 73 69 6f 6e 3a 20 39 2e 30 0d RP-Version:.9.0.
[V]     60 0a 52 50 2d 41 70 70 6c 69 63 61 74 69 6f 6e 2d .RP-Application-
[V]     70 52 65 61 73 6f 6e 3a 20 38 30 31 30 38 62 66 66 Reason:.80108bff
[V]     80 0d 0a 0d 0a                                     ....            
[E] Regist received HTTP code 403
[E] Reported Application Reason: 0x80108bff (unknown)
[E] Regist eventually failed

**Comment by KimblemZ** [comment]
I just got Chiaki today. I'm having a hard time on getting my Account ID. I'm using ubuntu studio 18.04. I'm not sure how to input the information into my terminal to get it. Having a hard time understanding the instructions. Generally I just copy and paste something like sudo apt get <deb name> or something but this is new to me.

**Comment by bbb1991** [comment]
@KimblemZ 
Open the console (via menu or hotkey `Ctrl+Alt+T`) and then paste following commands (one by one recommended):
```
# create temp dir
mkdir /tmp/test1
# change current dir
cd /tmp/test1
# create virtual environment
python -m venv venv
# activate virtual environment
source venv/bin/activate
# install required library
pip install requests
# download script
wget https://raw.githubusercontent.com/thestr4ng3r/chiaki/master/scripts/psn-account-id.py
# execute it
python psn-account-id.py
```
then follow instruction
P.S. Creating virtual environment may be different and require install additional package (used ubuntu very long time ago)

**Comment by KimblemZ** [comment]
Here is what I got so far and stopped when I got no command found.

/usr/bin/python: No module named venv

got this via "python -m venv vent"

**Comment by thestr4ng3r** [comment]
You don't necessarily have to use a venv. You can also install the python requests package from your distribution's packages if available. (Installing system-wide with pip is usually discouraged)

**Comment by KimblemZ** [comment]
> You don't necessarily have to use a venv. You can also install the python requests package from your distribution's packages if available. (Installing system-wide with pip is usually discouraged)

I can't seem to see it in the package manager. Is there a command line to to get the repository and then install it?

**Comment by thestr4ng3r** [comment]
On ubuntu that would be `sudo apt-get install python3-requests`

**Comment by KimblemZ** [comment]
$ python psn-account-id.py
DO NOT use Python 2.
EVER.
https://pythonclock.org

When trying to run it I get this. When i tried the python3-requests it says I already have it installed. Thanks for getting back to me so quickly thestr4ng3r. I generally have trouble with linux sometimes but the obstacles are the fun part right?

**Comment by thestr4ng3r** [comment]
Use `python3` instead of `python`

**Comment by KimblemZ** [comment]
I was able to register the ps4! though when trying to use it my new problem is this error "Chiaki Session has quit: Unkown error in Stream Connection.

**Comment by jaxjexjox** [comment]
CE-35406-8

[I] Regist starting search
[I] Regist sending search packet
[I] Regist received search response from 192.168.0.83
[I] Regist connected to 255.255.255.255, sending request
[I] Regist waiting for response
[E] Regist received HTTP code 403
[E] Reported Application Reason: 0x80108b02 (Invalid PSN ID)
[E] Regist eventually failed

**Comment by jaxjexjox** [comment]
Error from Chiaki with verbose logging enabled.

[V] Regist formatted request header:
[V] offset 0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f  0123456789abcdef
[V]      0 50 4f 53 54 20 2f 73 63 65 2f 72 70 2f 72 65 67 POST./sce/rp/reg
[V]     10 69 73 74 20 48 54 54 50 2f 31 2e 31 0d 0a 48 4f ist.HTTP/1.1..HO
[V]     20 53 54 3a 20 31 30 2e 30 2e 32 2e 31 35 0d 0a 55 ST:.10.0.2.15..U
[V]     30 73 65 72 2d 41 67 65 6e 74 3a 20 72 65 6d 6f 74 ser-Agent:.remot
[V]     40 65 70 6c 61 79 20 57 69 6e 64 6f 77 73 0d 0a 43 eplay.Windows..C
[V]     50 6f 6e 6e 65 63 74 69 6f 6e 3a 20 63 6c 6f 73 65 onnection:.close
[V]     60 0d 0a 43 6f 6e 74 65 6e 74 2d 4c 65 6e 67 74 68 ..Content-Length
[V]     70 3a 20 35 33 30 0d 0a 52 50 2d 56 65 72 73 69 6f :.530..RP-Versio
[V]     80 6e 3a 20 39 2e 30 0d 0a 0d 0a                   n:.9.0....      
[I] Regist starting search
[I] Regist sending search packet
[V] Regist received packet:
[V] offset 0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f  0123456789abcdef
[V]      0 53 52 43 32                                     SRC2            
[V] Regist received packet:
[V] offset 0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f  0123456789abcdef
[V]      0 52 45 53 32 01 05 00                            RES2...         
[I] Regist received search response from 192.168.0.83
[I] Regist connected to 255.255.255.255, sending request
[I] Regist waiting for response
[V] Regist response HTTP header:
[V] offset 0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f  0123456789abcdef
[V]      0 48 54 54 50 2f 31 2e 31 20 34 30 33 20 46 6f 72 HTTP/1.1.403.For
[V]     10 62 69 64 64 65 6e 0d 0a 43 6f 6e 6e 65 63 74 69 bidden..Connecti
[V]     20 6f 6e 3a 20 63 6c 6f 73 65 0d 0a 50 72 61 67 6d on:.close..Pragm
[V]     30 61 3a 20 6e 6f 2d 63 61 63 68 65 0d 0a 43 6f 6e a:.no-cache..Con
[V]     40 74 65 6e 74 2d 4c 65 6e 67 74 68 3a 20 30 0d 0a tent-Length:.0..
[V]     50 52 50 2d 56 65 72 73 69 6f 6e 3a 20 39 2e 30 0d RP-Version:.9.0.
[V]     60 0a 52 50 2d 41 70 70 6c 69 63 61 74 69 6f 6e 2d .RP-Application-
[V]     70 52 65 61 73 6f 6e 3a 20 38 30 31 30 38 62 30 32 Reason:.80108b02
[V]     80 0d 0a 0d 0a                                     ....            
[E] Regist received HTTP code 403
[E] Reported Application Reason: 0x80108b02 (Invalid PSN ID)
[E] Regist eventually failed

**Comment by jaxjexjox** [comment]
Apologies, didn't know remote play is USER SPECIFIC.
I was literally signed into the PS4 using my wifes account, once I signed in with mine, I'm in.  - very useful!

**Comment by qfung** [comment]
Hello Chiaki Team,
I am having issues as well:
[I] Regist starting search
[I] Regist sending search packet
[I] Regist received search response from 192.168.1.75
[I] Regist connected to 192.168.1.75, sending request
[I] Regist waiting for response
[E] Regist received HTTP code 403
[E] Reported Application Reason: 0x80108bff (unknown)
[E] Regist eventually failed

I have everything set the lowest setting on Chiaki.
Currently using firmware 7, logging in with my PSN ID.
I got a CE-35397-7 error.

**Comment by VoiciehBy** [comment]
It worked. What I've have done:
allowed firewall incoming.
Btw I'm using Linux Mint 19.3.

**Comment by thestr4ng3r** [comment]
Please don't comment on old issues. Check if there is one that matches your problem.
