### ISSUE TITLE
Possible to use 8bitdo 30SN Pro controller?

### ISSUE THREAD

**Issue by alx242** [thestr4ng3r/chiaki#54]
At the moment I can remote play using the DS4 and Chiak on Linux which is great. I'm wondering if it is possible to use for instance the 8bitdo 30SN Pro https://www.8bitdo.com/sn30-pro-g-classic-or-sn30-pro-sn/ controller or some other third-party controller?

**Comment by thestr4ng3r** [comment]
Anything supported by SDL Gamecontroller can be used. I have been using an SN30 Pro myself with Chiaki before. Is it not working for you?

**Comment by alx242** [comment]
Well last time I tried it it didn't. Currently I can't connect to my PS4 since the 7.00 update was deployed. I will try again as soon as I can :)

But you didn't do anything special to get it to work? No specific driver or such?

**Comment by thestr4ng3r** [comment]
I think I had to use it over Bluetooth. No specific driver on Arch Linux.

**Comment by alx242** [comment]
Tried it against the Chiaki-2378db19c6b7a56b105cb2e75da6e16cf2004eec-Linux-x86_64.AppImage you posted in another issue. It works like a charm :D Not sure why I couldn't get it to work the last time :)
