### ISSUE TITLE
More complete build instructions? 

### ISSUE THREAD

**Issue by MichaelVash7886** [thestr4ng3r/chiaki#55]
Can you provide a bit more detail in the build instructions? New to the idea of building from source. 

Running the app image in kubuntu 19.04 but cannot get the build option to work. The app image won't connect since I'm on 7.0 and was on the 7.0 beta for a while. It gives me a 403 error.

Looking forward to checking this out. I very cool project.

**Comment by Strubbl** [comment]
You can have a look into the Dockerfile i am working on. It is Ubuntu-based: https://github.com/thestr4ng3r/chiaki/pull/50/files

**Comment by thestr4ng3r** [comment]
Please share some details about what exactly doesn't work for you or what information you are missing.

**Comment by MichaelVash7886** [comment]
I managed to get it to build. It was a little confusing which of the words were actually packages when iyd
