### ISSUE TITLE
Unknown Session Request Error

### ISSUE THREAD

**Issue by Whovian9369** [thestr4ng3r/chiaki#57]
Hello! I decided to try [1.0.4-144](https://ci.appveyor.com/project/thestr4ng3r/chiaki/builds/27996255) via AppVoyer, and got [this lovely error message](https://user-images.githubusercontent.com/5240754/66535405-74d56d80-eae7-11e9-94ca-4c306440a166.png) when tyrying to connect to my 5.05 console playing Persona 5.

1.0.3 (Stable -- From the Github Releases page) proceeds to connect just fine. Can try to help some more if needed :)

Thanks for your time!

**EDIT:** Proceeded to enable Verbose Logging and tried connecting again and, well...

`[2019-10-09 22:53:19:105105] [E] Reported Application Reason: 0x80108b11 (Client outdated)`

[Here's the full 1.0.4-144 log, and thank you for your time!](https://github.com/thestr4ng3r/chiaki/files/3710251/chiaki_session_2019-10-09_22-53-14-574574.log)

**Edit:** It also, on a semi related note, seems that you accidentally have the log directory accidentally making `Chiaki\Chiaki` on the Windows build(s) of Chiaki, at the very least. An example: `AppData\Roaming\Chiaki\Chiaki\log\`

**Comment by miguit** [comment]
I have the same problem. was there update just fev days ago. I noticed that sony's own remote play udpated it self yesterday.

**Comment by thestr4ng3r** [comment]
@miguit If you are already on PS4 7.0, your issue would be #51, which is already fixed.

@Whovian9369 Thanks for reporting the incompatibility with < 7.0 after the version change, this will need a bit of compatibility code.

`Chiaki\Chiaki` is intended because it is how Qt lays out the directory.

**Comment by thestr4ng3r** [comment]
@Whovian9369 Please try this build: https://ci.appveyor.com/project/thestr4ng3r/chiaki/builds/28045391/artifacts
If you have time, please also try registration with it (you will have to select PSN Online-ID for PS4 < 7.0) so we know whether this works too.

**Comment by Whovian9369** [comment]
> `Chiaki\Chiaki` is intended because it is how Qt lays out the directory.
Cool, wanted to point it out anyway, just in case it was unintentional :)

> @Whovian9369 Please try this build: https://ci.appveyor.com/project/thestr4ng3r/chiaki/builds/28047950/artifacts
> If you have time, please also try registration with it (you will have to select PSN Online-ID for PS4 < 7.0) so we know whether this works too.
Can't test it right away, but I'll definitely try when I can!

**Comment by Whovian9369** [comment]
> 
> 
> @Whovian9369 Please try this build: https://ci.appveyor.com/project/thestr4ng3r/chiaki/builds/28047950/artifacts
> If you have time, please also try registration with it (you will have to select PSN Online-ID for PS4 < 7.0) so we know whether this works too.

I was only just able to test (mainly due to forgetting about this issue, apologies) and yep, that works! Can also confirm that the latest commit, [Build 186](https://ci.appveyor.com/project/thestr4ng3r/chiaki/builds/28182624/artifacts), works as well!
