### ISSUE TITLE
Any chance of a new release

### ISSUE THREAD

**Issue by abienz** [thestr4ng3r/chiaki#60]
Hello,

As of the date of this issue, the last release was 28 days ago, and since then the PS4 OS has been updated to v7, and Chiaki has had some other fixes pushed.

Is now a good time to create a new release? How often will they be created normally?

**Comment by thestr4ng3r** [comment]
1.0.4 is out


> How often will they be created normally?

whenever everything is stable enough.

**Comment by abienz** [comment]
Thank you.
