### ISSUE TITLE
how to discover my psn account id

### ISSUE THREAD

**Issue by Glaceon1** [thestr4ng3r/chiaki#63]
what do i do with the python script, i dont understand a thing about it

**Comment by b0mba1992** [comment]
psn-account-id syntax error(. I dont run this.

**Comment by termik88** [comment]
follow the link https://github.com/thestr4ng3r/chiaki/blob/master/scripts/psn-account-id.py and copy all the text. Сreate an empty file chiaki.py,  and insert text starting with  #!/usr/bin/env python3   # -*- coding: utf-8 -*-
Allow the execution of the file as a program. 
Go to the terminal and run the file with the command - python3 chiaki.py 
Follow the instructions.

**Comment by AstraAsura** [comment]
stucl at this     print("\"requests\" is not available. Install it with pip whatever.")

**Comment by termik88** [comment]
apt install python-pip
pip install requests

**Comment by Asfor-farah** [comment]
Hi, Aren't there an easier way to get the ID ?
cuz i'm not good with python , i tried to do it , but it didn't work for me :(
i used the latest version of python running with latest version of windows

**Comment by b0mba1992** [comment]
[https://drive.google.com/open?id=1ut9O_vTEx_2NvVt_8yjMzxO2rz49k8N8](url)
This is for python 3.7
1) install python 3.7
2) in terminal copy|paste command:
apt install python-pip3
pip3 install requests
3) download file 1.py (google url)
4) start 1.py

**Comment by Asfor-farah** [comment]
okay it work, but once i paste the url form the redirect page the terminal (cmd of 1.py ) disappear !
