### ISSUE TITLE
PSN Account ID Script Causes Crash

### ISSUE THREAD

**Issue by ZaybierOG** [thestr4ng3r/chiaki#65]
I am currently running Windows 10 build 1903 with Python 3.0.
Whenever I try running the script to get my Account ID it causes an instant crash to my command prompt.
I have attempted to run the script in Python as well, the same result occurs.

**Comment by termik88** [comment]
https://github.com/thestr4ng3r/chiaki/issues/63

**Comment by termik88** [comment]
You can download from this link
https://drive.google.com/open?id=1xYhg3dmakEZ5mwhUb0fnz9Fgsw0qQMSL

**Comment by thestr4ng3r** [comment]
Please don't share links to code I cannot verify here.

Of course you can "download" the file. Just `wget https://raw.githubusercontent.com/thestr4ng3r/chiaki/master/scripts/psn-account-id.py` or whatever.

What is an "instant crash to my command prompt"? How do you attempt to run the script? What happens exactly?

**Comment by ZaybierOG** [comment]
I copy and pasted the code from the file to Python. I also tried doing in my Command Prompt on Windows. Whenever I paste it into the command prompt it immediately crashes. The same result occurs on Python as well. Is this program only for Linux? Or can I also use it on Windows as well?

**Comment by ZaybierOG** [comment]
I have used a workaround to this issue, moved Ubuntu to a USB drive, and ran the script on Ubuntu instead. Sorry if I wasted anyone's time.

**Comment by termik88** [comment]
you needed to install python for windows and run a script through it.
