### ISSUE TITLE
Lib Release

### ISSUE THREAD

**Issue by valincius** [thestr4ng3r/chiaki#69]
I am trying to integrate Chiaki with my own application, could you include a release for the Window's .lib + .dll?

**Comment by thestr4ng3r** [comment]
I can, however Windows support is very low priority for me. Is there anything that prevents you from building it yourself? If you use cmake, you can just `add_subdirectory()` it for example.

**Comment by valincius** [comment]
I see, I just figured you’d already have them built, but I can try to build them myself, I’ll see if I can get a Docker set up and maybe you can add it to the CI/CD for this repo
