### ISSUE TITLE
SetThreadDescription not available on Windows 7

### ISSUE THREAD

**Issue by AstraAsura** [thestr4ng3r/chiaki#7]
i had installed Visual C++ 2015-2019 both x64 and x86 ... i'm using windows 7 pro 64bit

**Comment by thestr4ng3r** [comment]
What exactly are you trying to do? Where do you get an error?

**Comment by AstraAsura** [comment]
i'm trying to run chaki.exe then i this error
https://upanh.pro/image/HiHu7G

**Comment by thestr4ng3r** [comment]
I see, that makes more sense. I will fix this until the next release.
