### ISSUE TITLE
accountID script not working on linux or windows

### ISSUE THREAD

**Issue by DPoolAGP** [thestr4ng3r/chiaki#70]
Hi, i've tried the script on both windows 10 and ubuntu 19.04. In linux i get to the point where i copy the redirect link, and it just closes the terminal every single time. Windows just flat out crashes command prompt and python terminal. I was wondering if there is another way to get my account id?

**Comment by thestr4ng3r** [comment]
Don't double-click the file or anything. Run it from a command line like
```
python3 <filename>.py
```

**Comment by batGnat** [comment]
I used it last night, it was working, on Arch

**Comment by trialism** [comment]
How do you even copy the redirect link?! It appears only for a millisecond... @thestr4ng3r is there a better way?

**Comment by trialism** [comment]
I catched the link with an extension, but I get this:

```☠️  URL did not contain code parameter```

**Comment by thestr4ng3r** [comment]
What are you all doing with the script? The script doesn't close anything.

**Comment by thestr4ng3r** [comment]
Ah nvm, you mean the url from the browser, right? For me it always stays there. But you can also use your browser's developer tools to get a log of all network requests. It will show up there.

**Comment by trialism** [comment]
Yeah, I got that link but the script can't extract anything from it, even though I was able to copy the `client_id=....` part. But now I have to convert that to base64 for some reason...

**Comment by trialism** [comment]
It turns out it needs the "user_id" but there is no such thing in the redirects.

**Comment by thestr4ng3r** [comment]
Please tell me exactly what you are doing, what exactly happens and what exactly you are expecting. "doesn't work" or "doesn't show anything" says nothing. The script itself works, I just re-ran it.

**Comment by thestr4ng3r** [comment]
The url that you should copy looks like `https://remoteplay.dl.playstation.net/remoteplay/redirect?code=<...>`

**Comment by trialism** [comment]
@thestr4ng3r I started the script and I got what I posted earlier. I didn't get any link like in your latest comment.

**Comment by trialism** [comment]
Where can I get that link btw?

**Comment by trialism** [comment]
This doesn't say anything:

`This ID seems to be a unique identifier for a PSN Account and it can be obtained from the PSN after logging in using OAuth. `

**Comment by thestr4ng3r** [comment]
HOW do you "start" the script? What EXACTLY do you see? Just post a screenshot or something.

**Comment by trialism** [comment]
Irrelevant, I run the `python ...py` and then it runs and fails with the passed link. WHERE CAN I GET THE REMOTEPLAY LINK?

**Comment by trialism** [comment]
You know, this one: `https://remoteplay.dl.playstation.net/remoteplay/redirect?code=<...>`? WHERE is it? WHICH page should I visit? WHERE should I go? Your script won't work because you never specified WHICH link we need.

**Comment by thestr4ng3r** [comment]
This is going nowhere. I asked you multiple times for more info or a screenshot and you didn't give it. If you can see a `https://auth.api.sonyentertainmentnetwork.com/2.0/oauth...` url, then you can also see all the instructions the script prints. Those tell you where to get the code url.
