### ISSUE TITLE
Is this supposed to run with 5fps with a ps4 pro?

### ISSUE THREAD

**Issue by trialism** [thestr4ng3r/chiaki#74]
I enabled 1080p and I have a 450mbps internet connection. My PC is more than ready. The devices were connected to the home wifi with ethernet cables. And when I connect the ds4 controller with a usb cable, chiaki freezes. I'm on a fresh manjaro linux using nvidia.

**Comment by thestr4ng3r** [comment]
No, you should generally get the selected framerate (30/60). You might be experiencing the same issue as #32. Please try the bionic build at the bottom of the thread.
