### ISSUE TITLE
can you add Dualshok 3 support

### ISSUE THREAD

**Issue by gamernewone** [thestr4ng3r/chiaki#8]
It would be good

**Comment by thestr4ng3r** [comment]
Chiaki uses SDL Gamecontroller by default, which should pretty much support everything. What OS do you use? Check out this page too: https://github.com/gabomdq/SDL_GameControllerDB
I might consider adding a db like that to the builds by default.

**Comment by thestr4ng3r** [comment]
closed because of no response
