### ISSUE TITLE
can't connect using ubuntu 19.04

### ISSUE THREAD

**Issue by throwaway565656** [thestr4ng3r/chiaki#80]
Hi. I am having trouble connecting to my ps4. I am running ubuntu 19.04, i don't have a firewall turned on at the moment, and i am on a vlan that has just my ps4 and my laptop on it nothing else. When i launch Chiaki my ps4 shows up as detected but not registered. My ps4 is up to date (ver. 7.00) and I followed the instructions to get my psn account id. No matter what i do the register button on the register console window is always greyed out and i can't connect. Is there something i am doing wrong? if you need anymore info ask away.

**Comment by throwaway565656** [comment]
I forgot to add when i add my android phone to the vlan i can connect using the official remote app and official 2nd screen app. Thank you.

**Comment by thestr4ng3r** [comment]
You mean this button?
![Bildschirmfoto vom 2019-10-26 11-01-40](https://user-images.githubusercontent.com/1460997/67617119-21019e80-f7e0-11e9-9f3f-99217f7f7519.png)
Can you share a screenshot of what exactly you are entering?

**Comment by throwaway565656** [comment]
![image](https://user-images.githubusercontent.com/57023838/67624423-646b0580-f7fe-11e9-9afc-4205bfee99ae.png)
Hi. That is the button. i put in all 1's just as an example but it happens even when i fill out those fields with the account-id i got from the python script and my pin for my ps4. I tried it on another laptop i connected to the vlan and got the same issue. Both are running Ubuntu 19.04. Thank you.

**Comment by thestr4ng3r** [comment]
The pin must be exactly 8 digits long. It comes from your PS4 when you go into Settings -> Remote Play -> Add Device.

**Comment by throwaway565656** [comment]
Doh I was putting in my pin to unlock my ps4 not the add device one. Works like a charm. Thank you very much for your help.
