### ISSUE TITLE
Can't use ps4 controller or connect to stream

### ISSUE THREAD

**Issue by m77mcgowan** [thestr4ng3r/chiaki#81]
When I go to connect my dualshock controller to the remote play stream, I constantly keep getting the error:
Remote has disconnected from Stream Connection.
Reason: "Server shutting down".

I don't have this problem when I go and use the controller to sign into a guest account, only when I sign into my personal psn account. Any help to fix this problem is appreciated!

**Comment by thestr4ng3r** [comment]
That is the PS4's behavior. It will only allow one controller to be connected per user and Remote Play counts as a controller. If you want to use the controller through Chiaki, connect it to your PC, not the PS4. If you want to use Chiaki only as a monitor and have the controller directly connected to the PS4, register Chiaki with a second PSN account and connect the controller to the primary one.
