### ISSUE TITLE
Very low framerate (unplayable) on the newest 1.0.4

### ISSUE THREAD

**Issue by mtytula** [thestr4ng3r/chiaki#82]
Hello, I've read all closed issues about low framerate during remote play connection. I tried to download the 1.0.2 bionic version, but the file is gone. My PS4 is updated to the latest firmware version.

My setup:
PS4 (FAT? Not slim or pro)
Ubuntu 18.04.3 LTS / Kernel 5.0.0-32-generic / Nvidia-430 drivers (on intel is the same situation)

**Comment by thestr4ng3r** [comment]
You can always go to https://travis-ci.com/thestr4ng3r/chiaki, click on the bionic build and get the download link from the far end of the log. It seems to have failed for the current build, but here is a recent enough version: https://transfer.sh/5wSNQ/Chiaki-ffc7486b0d9636cd08c190c9ffee53ea51fe6d5a-Linux-x86_64.AppImage

**Comment by mtytula** [comment]
@thestr4ng3r, the build failed

`$ if [ ! -z "$DEPLOY_FILE" ]; then curl -m 300 --upload-file "$DEPLOY_FILE" "https://transfer.sh/$DEPLOY_FILE"; echo; fi
Could not save metadata
Could not save metadata
Could not save metadata
Skipping a deployment with the releases provider because a custom condition was not met
Skipping a deployment with the releases provider because this is not a tagged commit
Done. Your build exited with 0.`

**Comment by thestr4ng3r** [comment]
That's what I said. Try the AppImage from my comment above.

**Comment by mtytula** [comment]
![image](https://user-images.githubusercontent.com/36896606/67623565-1f0efe00-f827-11e9-9f63-eefa708ea836.png)

**Comment by thestr4ng3r** [comment]
Works for me, but it seems transfer.sh is generally flaky at the moment.

**Comment by mtytula** [comment]
That's strange for me. I tried to download with different browsers, but with no luck...

**Comment by thestr4ng3r** [comment]
Sorry, my fault. It is indeed broken. Seems like transfer.sh is completely broken right now.

**Comment by mtytula** [comment]
Any other ways to get the build?

**Comment by thestr4ng3r** [comment]
Unfortunately no, right now your best option is to build from source.

**Comment by mtytula** [comment]
I've got this file from link from your first post. It's working without any issues, but why?

**Comment by thestr4ng3r** [comment]
The exact cause is not known yet. It some a difference in the libraries shipped within the AppImage. Follow #32 if you are interested in this issue. I will close this one now because since this works for you, it is a duplicate.
