### ISSUE TITLE
Touchpad not working

### ISSUE THREAD

**Issue by enriquemorenotent** [thestr4ng3r/chiaki#84]
I am playing The Last Of Us Remastered. To open a certain menu, I have to press the touchpad, but in my case it is doing nothing at all.

**Comment by thestr4ng3r** [comment]
You can press T on the keyboard as a temporary workaround.

**Comment by enriquemorenotent** [comment]
Thanks, that will work for now

**Comment by jaxjexjox** [comment]
I could have sworn this worked initially for me, but stopped - I found the T option and it's workable for the game I'm playing, phew.

**Comment by thw0rted** [comment]
I asked the same thing on #53 but what's missing to be able to support this? I think it's already working in PStreamer so there must be some way to get at least the button click working. Does the controller have to be put into a separate mode?

**Comment by bteamfox** [comment]
Detroit: Become Human, I can not play this game as the game requires directional swiping on the touchpad, (swipe, left-right, left, etc). I hope this function can be added soon as this program is fantastic and runs like a charm on my Linux Mint PC.

**Comment by thestr4ng3r** [comment]
The protocol part for touchpad has not been implemented so a quick fix is not possible.

**Comment by bteamfox** [comment]
> The protocol part for touchpad has not been implemented so a quick fix is not possible.

Ah, I understand now. Thank you for your very quick reply. I look forward to a version with the protocol part add. 😀👍

**Comment by enriquemorenotent** [comment]
Pressing T only seems to work once... :/

**Comment by OrigWhiteKenyan** [comment]
Hi, so I was trying to play Okami tonight and the first thing I ran into was not being able to use the "T" workaround to actually start the game haha. If anyone could help me out with this, it would be appreciated. Thanks

**Comment by thestr4ng3r** [comment]
Touchpad support is now available, but currently only on Linux and only from an actual Dualshock 4 controller connected over usb or bluetooth. Further progress will be tracked in #270.
