### ISSUE TITLE
Shaking dualshock not working

### ISSUE THREAD

**Issue by enriquemorenotent** [thestr4ng3r/chiaki#85]
I am playing The Last Of Us Remastered. There is an section where I have to shake the controller to make it perform an action (most likely, climbing the ladder) but it does not seem to work.

![Peek 2019-10-27 18-52](https://user-images.githubusercontent.com/368842/67638995-06681c00-f8eb-11e9-88ff-48b94e1903cd.gif)

**Comment by thestr4ng3r** [comment]
Accelerometer/gyroscope is not yet implemented, but planned.

**Comment by hacker-lc** [comment]
@thestr4ng3r Thank you very much for your work.

A source of reference about the DS4 Controller State including the Gyro and Touch pad. For your information.
[https://github.com/komefai/PS4RemotePlayInterceptor/blob/master/PS4RemotePlayInterceptor/Classes/DualShockState.cs](url)

**Comment by thestr4ng3r** [comment]
will be tracked in #53
