### ISSUE TITLE
Install it with pip whatever

### ISSUE THREAD

**Issue by fares454545** [thestr4ng3r/chiaki#86]
Hi,

Sorry for this stupid question, i do not find pip whatever. is it this one https://pypi.org/project/whatever/ ?
I have tried several time to install it, not working on my side

**Comment by thestr4ng3r** [comment]
No, you just have to install requests like `pip3 install requests`

**Comment by fares454545** [comment]
Thanks did it. but i am blocked here now

![image](https://user-images.githubusercontent.com/57073996/67641291-a03ac380-f901-11e9-9dd5-9c745010c245.png)
