### ISSUE TITLE
Controller Vibration

### ISSUE THREAD

**Issue by kaikun97** [thestr4ng3r/chiaki#89]
On Chiaki 1.0.4 it appears that vibration is not working in any game that I try when using the DS4 controller. Vibration is enabled in the system settings as is the setting on supported games. I have confirmed vibration works on the official Remote Play software.

**Comment by thestr4ng3r** [comment]
Rumble is not yet implemented, but planned of course.

**Comment by thestr4ng3r** [comment]
Tracked in #17
