### ISSUE TITLE
Remote play stops/lose connection right after start

### ISSUE THREAD

**Issue by AbuMegatron** [thestr4ng3r/chiaki#95]
First of all thx for that cool App, running LOS 14.1 on my Samsung Note 10.1(GT N8000)

Now I don't need to buy pstreamer :)

 ... but unfortunately it does not work for me.. 
At the moment I don't know why -.- I'm paired now and see my playstation inside the app.

If I press on the connect icon (Tablet) I see remote play started but right after then get a notification that remote play has been shut down (all on my playstation) what did I wrong? 

On my tablet I don't get an error code.

**Comment by thestr4ng3r** [comment]
Please share a log of when this happened from Settings->Session Logs

**Comment by AbuMegatron** [comment]
I only get emty log files... 
But i see for a short time i get the notification "no consoles added of discovered" 


If i try IT really fast i get this... 

[I] Logging to file /data/user/0/com.metallic.chiaki/files/session_logs/chiaki_session_2019-11-04_23-09-25-888.log
[I] Start JNI Session
[I] Starting session request
[I] Trying to request session from PS4-3753C0.fritz.box:9295
[I] Connected to PS4-3753C0.fritz.box:9295
[I] Sending session request
[E] Reported Application Reason: 0x80108b10 (Remote is already in use)
[I] Session has quit
[I] Stop JNI Session
[I] Join JNI Session
[I] Shutting down JNI Session
[I] Video Decoder sending EOS buffer
[I] AMediaCodec reported EOS
[I] Video Decoder Output Thread exiting
[I] JNI Session has quit

**Comment by AbuMegatron** [comment]
I still don't find a way to start remote play and get the session log... just "no consoles added or discovered"

Help please...

**Comment by thestr4ng3r** [comment]
This seems to be a crash, I am investigating the cause.

**Comment by thestr4ng3r** [comment]
Confirmed, there are some alignment issues on 32 bit ARM.

**Comment by AbuMegatron** [comment]
> Confirmed, there are some alignment issues on 32 bit ARM.

Ah ok thx for the replay, so I have to wait till it get fixed.. (will there be a fix?)

**Comment by thestr4ng3r** [comment]
Please try version 1.1.1. It should also be live on the Play Store in the next hour or so.

**Comment by AbuMegatron** [comment]
Ok i will try it thx a lot!

**Comment by AbuMegatron** [comment]
Hello i tryed the New Version 1.1.1.
But now i cant even registrate the PS4

I get this

[V] Regist formatted request header:
[V] offset 0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f  0123456789abcdef
[V]      0 50 4f 53 54 20 2f 73 63 65 2f 72 70 2f 72 65 67 POST./sce/rp/reg
[V]     10 69 73 74 20 48 54 54 50 2f 31 2e 31 0d 0a 48 4f ist.HTTP/1.1..HO
[V]     20 53 54 3a 20 31 30 2e 30 2e 32 2e 31 35 0d 0a 55 ST:.10.0.2.15..U
[V]     30 73 65 72 2d 41 67 65 6e 74 3a 20 72 65 6d 6f 74 ser-Agent:.remot
[V]     40 65 70 6c 61 79 20 57 69 6e 64 6f 77 73 0d 0a 43 eplay.Windows..C
[V]     50 6f 6e 6e 65 63 74 69 6f 6e 3a 20 63 6c 6f 73 65 onnection:.close
[V]     60 0d 0a 43 6f 6e 74 65 6e 74 2d 4c 65 6e 67 74 68 ..Content-Length
[V]     70 3a 20 35 33 30 0d 0a 52 50 2d 56 65 72 73 69 6f :.530..RP-Versio
[V]     80 6e 3a 20 39 2e 30 0d 0a 0d 0a                   n:.9.0....      
[I] Regist starting search
[I] Regist sending search packet
[V] Regist received packet:
[V] offset 0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f  0123456789abcdef
[V]      0 53 52 43 32                                     SRC2            
[E] Regist timed out waiting for search response
[E] Regist search failed

**Comment by thestr4ng3r** [comment]
This is more likely a network issue on your side. There have been no changes in the registration process.

**Comment by AbuMegatron** [comment]
Hallo, sry for the late response.
It works now! It is connected now.

I was a bit busy the last couple of days but I will try the functionality in depth next and report to you.
Thx a lot for the support.

**Comment by thestr4ng3r** [comment]
No problem, thanks for testing! Feel free to open new issues if you encounter any more bugs.

**Comment by Dami91** [comment]
I'm losing my connection with the remote play after 5 to 10 min from my connected with PS4, I keep trying how to fix it cuz I'm streaming and I lose the connection from ps4 remote play please if someone can help thank you.
