### ISSUE TITLE
How do I do, full - full screen? (not just maximised?)

### ISSUE THREAD

**Issue by jaxjexjox** [thestr4ng3r/chiaki#96]
Is it even possible? Ubuntu 19.10.

**Comment by thestr4ng3r** [comment]
F11

**Comment by jaxjexjox** [comment]
Thanks for the help.

Do you know where I can post to get information on increasing performance (or how I can help diagnose issues?)

At 720P on a 5Ghz wifi connection (Around 600Mbit apparently, only 7' away)  it seems pretty much flawless.      
When I crank it up to 1080P  the performance is fine but frames get dropped and droopy. Very similar graphical glitches as VLC media player when a byte is screwed up.
Also sound pops and glitches.  I changed the sound buffer to 19200 instead, it reduced this.

Should I try Windows just to be 10,000% sure it's possible to do on my hardware first (I can re-install, I don't mind - rather not, but I can do it so that the testing is very thorough)

**Comment by thestr4ng3r** [comment]
Please make a new issue about that including logs and more details about your environment. Don't bother trying on Windows, it is the least maintained version.
